import asyncio, base64, io, zipfile, json, sys
from harness import *

OK = []
def check(name, cond, extra=""):
    OK.append((name, bool(cond)))
    print(("PASS " if cond else "FAIL ") + name + (" · " + str(extra) if extra else ""))

async def main():
    async with async_playwright() as p:
        b, pg, errs = await open_page(p, w=1440, h=900, theme="dark", hash_="diario")
        ev = pg.evaluate
        # ---------- diário: compositor, autocompletar, comandos
        await pg.click(".czopen"); await pg.wait_for_timeout(200)
        ta = pg.locator("#dz_texto")
        await ta.click(); await ta.type("Almoço com @Ma", delay=10)
        await pg.wait_for_timeout(150)
        ac_vis = await ev("!document.getElementById('ac').hidden")
        items = await ev("[...document.querySelectorAll('#ac .aci b')].map(x=>x.textContent)")
        check("autocompletar @ abre com pessoas", ac_vis and any("Marco" in i or "Mãe" in i for i in items), items)
        await pg.keyboard.press("Enter")
        val = await ev("document.getElementById('dz_texto').value")
        check("autocompletar insere a menção", "@M" in val and val.endswith(" "), val)
        await ta.type("no centro. #trabalho [[Meta: Concluir", delay=5)
        await pg.wait_for_timeout(120)
        items = await ev("[...document.querySelectorAll('#ac .aci b')].map(x=>x.textContent)")
        check("autocompletar [[ lista metas", any("Concluir o Master BIM" in i for i in items), items[:3])
        await pg.keyboard.press("Enter")
        await ta.press("End"); await ta.type("\n/gasto 23,40 Restaurantes & cafés: almoço\n/tarefa Mandar portfólio até 20/10 !alta\n- [ ] ligar para o banco", delay=2)
        await pg.wait_for_timeout(200)
        live = await ev("document.getElementById('dz_live').innerText")
        check("prévia detecta comandos", "Despesa de" in live and "Tarefa: Mandar portfólio" in live, live.replace("\n", " | ")[:200])
        n_lanc = await ev("S.lanc.length"); n_tar = await ev("S.tarefas.length"); n_dia = await ev("S.diario.length")
        await pg.click('[data-act="dzsave"]'); await pg.wait_for_timeout(300)
        check("entrada salva", await ev("S.diario.length") == n_dia + 1)
        check("comando /gasto criou lançamento", await ev("S.lanc.length") == n_lanc + 1, await ev("JSON.stringify(S.lanc.at(-1))"))
        check("comando /tarefa criou tarefa com prazo e prioridade", await ev("S.tarefas.at(-1).tarefa === 'Mandar portfólio' && S.tarefas.at(-1).prio === 'Alta' && S.tarefas.at(-1).prazo.endsWith('-10-20')"), await ev("JSON.stringify(S.tarefas.at(-1))"))
        await pg.wait_for_timeout(1500)
        check("exemplo virou dado do usuário e gravou", await ev("!IS_EXAMPLE") and await ev("window.__dbw") > 0 and await ev("KEYS.every(k => window.__store['data/users/u_test/s_' + k])"), await ev("window.__dbw"))
        # salvamos em documentos menores que 256 KiB
        sizes = await ev("Object.entries(window.__store).map(([k,v])=>[k, JSON.stringify(v).length]).sort((a,b)=>b[1]-a[1]).slice(0,4)")
        check("documentos do banco < 256 KiB", all(s < 262144 for _, s in sizes), sizes)
        # desfazer
        await pg.keyboard.press("Control+z"); await pg.wait_for_timeout(200)
        check("Ctrl+Z desfaz a entrada e os registros", await ev("S.diario.length") == n_dia and await ev("S.lanc.length") == n_lanc, await ev("[S.diario.length, S.lanc.length]"))
        await pg.keyboard.press("Control+Shift+z"); await pg.wait_for_timeout(200)
        check("Ctrl+Shift+Z refaz", await ev("S.diario.length") == n_dia + 1 and await ev("S.lanc.length") == n_lanc + 1)
        # checklist interativa e ficha de pessoa
        await pg.wait_for_timeout(200)
        before = await ev("S.diario.find(e=>e.texto.includes('ligar para o banco')).texto.includes('[x]')")
        await pg.locator("#e_" + await ev("S.diario.find(e=>e.texto.includes('ligar para o banco')).id") + " input[data-ck]").first.click()
        await pg.wait_for_timeout(200)
        after = await ev("S.diario.find(e=>e.texto.includes('ligar para o banco')).texto.includes('- [x] ligar')")
        check("marcar item da lista altera o texto", (not before) and after)
        await pg.locator(".ent-body .mn:not(.unk)").first.click(); await pg.wait_for_timeout(250)
        check("menção abre a ficha da pessoa", await ev("!!document.querySelector('#drawer')") and await ev("document.querySelector('#drawer h2').textContent.length > 1"), await ev("document.querySelector('#drawer h2')?.textContent"))
        bl = await ev("document.querySelectorAll('#drawer .bl').length")
        check("ficha mostra entradas que citam a pessoa", bl >= 1, bl)
        await pg.keyboard.press("Escape"); await pg.wait_for_timeout(150)
        # filtro por tema
        await ev("Object.assign(DIA,{q:'',tag:null,pessoa:null,area:null,mood:null,pin:false,per:'all'}); render()")
        await pg.locator('[data-dtag="familia"]').first.click(); await pg.wait_for_timeout(200)
        shown = await ev("document.querySelectorAll('.ent').length"); expected = await ev("S.diario.filter(e=>parseEntry(e.texto).tags.includes('familia')).length")
        check("filtro por #tema", shown == expected and shown > 0, (shown, expected))
        # ---------- mentores com ferramentas
        await ev("location.hash='mentor.fin'"); await pg.wait_for_timeout(500)
        mem0 = await ev("mget('fin').mem.length"); conv0 = await ev("mget('fin').conversa.length")
        await pg.fill("#m_in", "Como estou nas finanças?"); await pg.click('[data-act="msend"]')
        await pg.wait_for_timeout(2500)
        calls = await ev("window.__calls.filter(c=>c.kind==='sample')")
        last = calls[-1]
        check("mentor chamou o Claude com turnos válidos e ferramentas", isinstance(last["input"], list) and last["input"][0]["role"] == "user" and "salvar_memoria" in last["tools"] and last["cache"] is False, last["tools"])
        prompt = last["input"][0]["content"]
        check("contexto do mentor tem dados, memória e plano", "Orçamento do mês por categoria" in prompt and "MEMÓRIA" in prompt and "PLANO ATUAL" in prompt, len(prompt))
        check("ferramentas de leitura rodaram (consultar/cruzar/diário)", any(c.get("name") == "consultar" for c in await ev("window.__calls")) and any(c.get("name") == "cruzar" for c in await ev("window.__calls")))
        check("memória salva pelo agente", await ev("mget('fin').mem.length") == mem0 + 1)
        check("plano atualizado pelo agente", await ev("mget('fin').plano.foco") == "Fechar o mês dentro do orçamento")
        check("recado deixado para o mentor do Lazer", await ev("mget('laz').mem.some(m=>m.tipo==='recado')"))
        check("conversa gravada (pergunta + resposta)", await ev("mget('fin').conversa.length") == conv0 + 2)
        props = await ev("document.querySelectorAll('[data-prop$=\"|ok\"]').length")
        check("proposta aparece para aprovação", props >= 1, props)
        nt = await ev("S.tarefas.length")
        await pg.locator('[data-prop$="|ok"]').last.click(); await pg.wait_for_timeout(250)
        check("aprovar proposta cria a tarefa", await ev("S.tarefas.length") == nt + 1 and await ev("S.tarefas.at(-1).origem") == "Mentor do Dinheiro", await ev("S.tarefas.at(-1).tarefa"))
        uso = await ev("document.querySelectorAll('.mchat .uso').length")
        check("chips mostram o que o agente fez", uso >= 4, uso)
        # plano: virar tarefa
        nt = await ev("S.tarefas.length")
        await pg.locator('[data-ptask]').first.click(); await pg.wait_for_timeout(200)
        check("passo do plano vira tarefa", await ev("S.tarefas.length") == nt + 1)
        # ---------- cruzamento: clique numa célula da matriz
        await ev("location.hash='cruz'"); await pg.wait_for_timeout(500)
        await pg.locator('.cc[data-cx]').nth(3).click(); await pg.wait_for_timeout(300)
        cz = await ev("[CZ.x, CZ.y]")
        check("matriz de correlação define X e Y", cz[0] != "sono" or cz[1] != "bem", cz)
        await pg.select_option("#czlag", "1"); await pg.wait_for_timeout(250)
        check("defasagem aplicada", await ev("CZ.lag") == 1)
        # ---------- filtro cruzado em Finanças
        await ev("location.hash='fin.rel'"); await pg.wait_for_timeout(500)
        await pg.locator('.tm[data-xf]').first.click(); await pg.wait_for_timeout(300)
        xfc = await ev("document.querySelector('.xfbar')?.innerText || ''")
        check("clicar no mapa de categorias filtra o relatório", "Categoria" in xfc, xfc[:80])
        rows = await ev("document.querySelectorAll('[data-vid=\"fin-top\"] tbody tr').length")
        cat = await ev("xf().cat"); expected = await ev(f"calcAt(REF).lm.filter(l=>l.tipo==='Despesa'&&l.cat==={json.dumps(cat)}).length")
        check("tabela de despesas respeita o filtro", rows == min(12, expected), (rows, expected, cat))
        await pg.locator('[data-vtab="fin-tm"]').click(); await pg.wait_for_timeout(200)
        check("visual vira tabela", await ev("!!document.querySelector('[data-vid=\"fin-tm\"] table')"))
        await pg.locator('[data-vfocus="fin-sk"]').click(); await pg.wait_for_timeout(200)
        check("modo foco abre", await ev("document.getElementById('focusdlg').open"))
        await pg.keyboard.press("Escape")
        # ---------- paleta de comandos
        await pg.keyboard.press("Control+k"); await pg.wait_for_timeout(150)
        await pg.keyboard.type("/gasto 4,50 café")
        await pg.wait_for_timeout(150)
        nl = await ev("S.lanc.length")
        await pg.keyboard.press("Enter"); await pg.wait_for_timeout(250)
        check("paleta executa comando rápido", await ev("S.lanc.length") == nl + 1 and await ev("S.lanc.at(-1).cat") == "Restaurantes & cafés", await ev("JSON.stringify(S.lanc.at(-1))"))
        await pg.keyboard.press("Control+k"); await pg.keyboard.type("chiara"); await pg.wait_for_timeout(150)
        await pg.keyboard.press("Enter"); await pg.wait_for_timeout(250)
        check("paleta encontra pessoa e abre a ficha", await ev("document.querySelector('#drawer h2')?.textContent") == "Chiara")
        await pg.keyboard.press("Escape")
        # ---------- editor de dados
        await ev("location.hash='dados.tarefas'"); await pg.wait_for_timeout(400)
        first = pg.locator('input[data-cell$="|tarefa"]').first
        old = await first.input_value()
        await first.fill("Tarefa editada na planilha"); await first.press("Tab"); await pg.wait_for_timeout(250)
        check("célula editada grava no estado", await ev("S.tarefas.some(t=>t.tarefa==='Tarefa editada na planilha')"))
        await pg.locator("body").click(position={"x": 5, "y": 5}); await pg.keyboard.press("Control+z"); await pg.wait_for_timeout(200)
        check("desfazer edição de célula", await ev(f"S.tarefas.some(t=>t.tarefa==={json.dumps(old)})") and not await ev("S.tarefas.some(t=>t.tarefa==='Tarefa editada na planilha')"))
        await pg.locator('input[data-dgsel]').nth(0).check(); await pg.locator('input[data-dgsel]').nth(1).check(); await pg.wait_for_timeout(150)
        await pg.select_option("#dg_bf", "prio"); await pg.wait_for_timeout(150); await pg.select_option("#dg_bv", "Baixa"); await pg.click('[data-act="dgbulk"]'); await pg.wait_for_timeout(200)
        check("alteração em massa", await ev("S.tarefas.filter(t=>t.prio==='Baixa').length") >= 2)
        # importação CSV de extrato
        await ev("location.hash='integ'"); await pg.wait_for_timeout(400)
        csv = "Data;Descrição;Valor\n01/10/2026;ESSELUNGA MILANO;-45,30\n01/10/2026;Stipendio ottobre;2450,00\n02/10/2026;Netflix;-9,99\n"
        await pg.set_input_files("#imp_bank", files=[{"name": "extrato.csv", "mimeType": "text/csv", "buffer": csv.encode()}]); await pg.wait_for_timeout(400)
        prev = await ev("document.querySelector('#impf')?.innerText || ''")
        check("assistente de importação abre com prévia", "3 linhas válidas" in prev.lower(), prev[:160].replace("\n", " | "))
        nl = await ev("S.lanc.length"); await pg.click("#impok"); await pg.wait_for_timeout(250)
        last3 = await ev("S.lanc.slice(-3).map(l=>[l.tipo,l.cat,l.valor])")
        check("extrato importado e categorizado", await ev("S.lanc.length") == nl + 3 and last3[0][1] == "Mercado" and last3[1][0] == "Receita" and last3[2][1] == "Assinaturas", last3)
        # Notion: buscar, ver, importar tarefas, exportar
        await pg.fill("#nt_q", "plano"); await pg.click('[data-act="ntsearch"]'); await pg.wait_for_timeout(400)
        check("busca no Notion lista páginas", await ev("document.querySelectorAll('[data-ntpv]').length") == 2)
        await pg.locator('[data-ntpv="pg1"]').click(); await pg.wait_for_timeout(400)
        pv = await ev("document.querySelector('.ntpv pre')?.textContent || ''")
        check("prévia da página do Notion, sem marcações", "Revisar capítulo 3" in pv and "<" not in pv and "Here is the result" not in pv and "color=" not in pv, pv[:120])
        nt = await ev("S.tarefas.length"); await pg.click('[data-act="ntimptasks"]'); await pg.wait_for_timeout(250)
        check("caixas abertas do Notion viram tarefas", await ev("S.tarefas.length") == nt + 2 and await ev("S.tarefas.at(-2).prio") == "Alta", await ev("S.tarefas.slice(-2).map(t=>t.tarefa+'|'+t.prazo+'|'+t.prio)"))
        await pg.click('[data-act="ntmonth"]'); await pg.wait_for_timeout(400)
        mc = [c for c in await ev("window.__calls") if c.get("kind") == "mcp" and c.get("tool") == "notion-create-pages"]
        check("relatório enviado ao Notion como rascunho", mc and mc[-1]["input"].get("creation_mode") == "draft" and "Áreas" in mc[-1]["input"]["pages"][0]["content"])
        check("histórico guarda o link da página", await ev("S.integ.notion.hist[0]?.url") == "https://app.notion.com/p/new1abc")
        # exportações
        for act in ["xbackup", "xvault", "xcal", "xtodoist"]:
            await pg.click(f'[data-act="{act}"]'); await pg.wait_for_timeout(300)
        saved = await ev("window.__saved.map(s=>s.filename)")
        check("4 arquivos oferecidos para download", len(saved) == 4, saved)
        files = await ev("window.__saved")
        z = next(f for f in files if f["filename"].endswith(".zip"))
        zf = zipfile.ZipFile(io.BytesIO(base64.b64decode(z["b64"])))
        names = zf.namelist(); bad = zf.testzip()
        md = zf.read([n for n in names if n.startswith("Atlas da Vida/Diário/")][-1]).decode()
        check("ZIP do cofre é válido e tem notas com [[ligações]]", bad is None and any(n.startswith("Atlas da Vida/Pessoas/") for n in names) and "---" in md, (len(names), md[:120].replace("\n", " | ")))
        cal = base64.b64decode(next(f for f in files if "agenda" in f["filename"])["b64"]).decode()
        check("CSV da agenda no formato do Google", cal.startswith("Subject,Start Date,Start Time,End Date,End Time,All Day Event") and "/2026" in cal, cal.splitlines()[1][:90])
        td = base64.b64decode(next(f for f in files if "todoist" in f["filename"])["b64"]).decode()
        check("CSV do Todoist com seções e prioridades", td.startswith("TYPE,CONTENT,DESCRIPTION,PRIORITY,INDENT") and "\r\nsection," in td and ",1,1," in td, td.splitlines()[1][:80])
        bk = json.loads(base64.b64decode(next(f for f in files if f["filename"].endswith(".json"))["b64"]).decode())
        check("backup JSON completo", set(bk["dados"].keys()) >= {"diario", "mentores", "lanc"})
        # recarregar: dados voltam do banco
        await ev("flushSoon(0)"); await pg.wait_for_timeout(1500)
        store = await ev("JSON.stringify(window.__store)")
        await pg.evaluate("window.__keep = 1")
        errs2 = [e for e in errs if "Failed to load resource" not in e]
        check("sem erros no console", not errs2, errs2[:3])
        await b.close()
    print(f"\n{sum(1 for _, ok in OK if ok)}/{len(OK)} passaram")

asyncio.run(main())
