
/* ================================================================ relatórios (estilo Power BI): grade de 12 colunas, filtros cruzados, trilho de contexto */
let REPW = 1100;
const railOn = () => innerWidth >= 1500;
function vw(span) { const G = REPW, gap = 16, pad = 34; let s = span; if (G < 760) s = 12; else if (G < 1080) s = span >= 7 ? 12 : 6; const col = (G - gap * 11) / 12; return Math.max(280, Math.round(s * col + (s - 1) * gap - pad)); }
function linProj(vals, k) { const p = vals.map((v, i) => ({ x: i, y: v })).filter(q => isNum(q.y)); if (p.length < 3) return []; const mx = avg(p.map(q => q.x)), my = avg(p.map(q => q.y)); let a = 0, b = 0; for (const q of p) { a += (q.x - mx) * (q.y - +my); b += (q.x - mx) ** 2; } const sl = b ? a / b : 0; return Array.from({ length: k }, (_, i) => my + sl * (vals.length + i - mx)); }
const projLabels = k => Array.from({ length: k }, (_, i) => mabbr(addMonth(REF, i + 1)));
const pctDelta = (cur, base) => delta(cur == null ? null : cur * 100, base == null ? null : base * 100, { fmt: v => num(v, 0), unit: " pp" });
function reportPage(R, H, kpis, body, areas) { return `${slicers()}${xfBar()}<div class="rep"><div class="repmain">${kpis ? kpiRow(kpis) : ""}<div class="vg">${body}</div></div>${rail(R, H, areas)}</div>`; }
function mentorMini(mid) {
  const def = MENTOR_DEF[mid], m = mget(mid), nx = m.plano?.passos.find(p => !p.feito);
  return `<div class="pn mmini" style="--c:${mcol(mid)}"><header>${mavatar(mid)}<div><a href="#mentor.${mid}"><b>${esc(def.nome)}</b></a><small>${m.plano ? esc(trunc(m.plano.foco, 70)) : "Sem plano ainda"}</small></div></header>${nx ? `<div class="mnext">${ic("arrow")}<span>${esc(nx.texto)}${nx.prazo ? ` <em class="muted">· ${relDay(nx.prazo)}</em>` : ""}</span></div>` : ""}<div class="mqk"><input id="mq_${mid}" type="text" placeholder="Pergunte ao ${esc(def.nome)}…" aria-label="Pergunta para o ${esc(def.nome)}"><button type="button" class="iconbtn" data-mquick="${mid}" aria-label="Enviar">${ic("send")}</button></div></div>`;
}
function rail(R, H, areas) {
  const ins = insights(R, H).filter(i => !areas || areas.includes(i.area)).slice(0, 4), mids = areas ? areas.map(a => AREA_INFO[a].id).slice(0, 2) : ["conselho"];
  return `<aside class="rail" aria-label="Contexto">${mids.map(mentorMini).join("")}${panel(`${ic("bolt")}O que os dados dizem`, ins.map(i => `<div class="insight ${i.st}"><div class="ik">${esc(i.k)}</div><p>${i.t}</p><p class="ia">${esc(i.a)}</p></div>`).join("") || `<div class="empty">Registre algumas semanas de dados para ver padrões aqui.</div>`)}</aside>`;
}
function agenda(R, days = 14, max = 40) {
  const until = addDays(TODAY, days), ev = [];
  R.tar.filter(t => t.open && t.prazo && t.prazo <= until).forEach(t => ev.push({ d: t.prazo, l: t.tarefa, s: t.projeto || (t.area ? ashort(t.area) : "tarefa"), ico: "checksq", ent: `tar|${t.id}`, a: t.area }));
  R.pes.filter(p => p.prox && p.prox <= until).forEach(p => ev.push({ d: p.prox, l: `Aniversário de ${p.nome}`, s: p.relacao, ico: "heart", ent: `p|${p.nome}`, a: relArea(p.relacao) }));
  R.docs.filter(d => d.validade && d.validade <= until).forEach(d => ev.push({ d: d.validade, l: `Vence: ${d.doc}`, s: d.acao || "documento", ico: "file", ent: `doc|${d.id}`, a: "Casa & organização" }));
  R.rot.filter(r => r.prox && r.prox <= until).forEach(r => ev.push({ d: r.prox, l: r.rotina, s: "rotina", ico: "repeat", a: "Casa & organização", done: r.id }));
  S.cand.filter(c => c.dataAcao && c.dataAcao <= until && !["Aceito", "Recusado", "Desisti"].includes(c.etapa)).forEach(c => ev.push({ d: c.dataAcao, l: `${c.acao || "Próxima ação"} · ${c.empresa}`, s: "candidatura", ico: "brief", a: "Carreira" }));
  R.metas.filter(m => m.ativa && m.rt !== "Concluída" && m.prazo && m.prazo <= until).forEach(m => ev.push({ d: m.prazo, l: `Prazo da meta: ${m.meta}`, s: m.rt, ico: "target", ent: `meta|${m.id}`, a: m.area }));
  for (const mid of MIDS) for (const p of mget(mid).plano?.passos || []) if (!p.feito && p.prazo && p.prazo <= until) ev.push({ d: p.prazo, l: p.texto, s: MENTOR_DEF[mid].nome, ico: "flag", a: MENTOR_DEF[mid].area, go: `mentor.${mid}` });
  for (const e of S.eventos || []) if (e.data >= TODAY && e.data <= until) ev.push({ d: e.data, l: `${e.hora ? e.hora + " · " : ""}${e.titulo}`, s: e.local || "agenda", ico: "cal", a: null, edit: e.id });
  const f = xf(), all = ev.filter(e => !f.area || e.a === f.area).sort((a, b) => a.d.localeCompare(b.d)), list = all.slice(0, max), by = {};
  for (const e of list) (by[e.d < TODAY ? "late" : e.d] ||= []).push(e);
  return Object.keys(by).length ? `<div class="agenda">${Object.entries(by).map(([d, es]) => `<div class="agd"><div class="agh${d === "late" ? " st-crit" : d === TODAY ? " now" : ""}">${d === "late" ? "Atrasado" : d === TODAY ? "Hoje" : d === addDays(TODAY, 1) ? "Amanhã" : fmtDL(d)}</div>${es.map(e => `<button type="button" class="agi" ${e.ent ? `data-ent="${esc(e.ent)}"` : e.go ? `data-go="${e.go}"` : e.done ? `data-done="${e.done}" title="Marcar a rotina como feita hoje"` : e.edit ? `data-edit="eventos" data-id="${e.edit}"` : ""} style="--c:${e.a ? acol(e.a) : "var(--muted)"}">${ic(e.ico)}<span>${esc(e.l)}<small>${esc(e.s)}${d === "late" ? " · " + fmtD(e.d) : ""}</small></span></button>`).join("")}</div>`).join("")}${all.length > list.length ? `<div class="more">+ ${plural(all.length - list.length, "item", "itens")} até ${fmtD(until)} · exporte tudo para o Google Agenda em <a class="lnk" href="#integ">Integrações</a></div>` : ""}</div>` : `<div class="empty">Nada marcado para os próximos ${days} dias.</div>`;
}

/* ---------------------------------------------------------------- Visão geral */
function rOverview(R) {
  const H = history(PER), L = H.map(h => mabbr(h.mk)), K = H.map(h => h.mk), f = xf(), C = S.cfg;
  const has = h => h.diasReg || h.fin.rec + h.fin.desp || h.hab.some(x => x.feitos);
  const idx = H.map(h => has(h) ? h.indice : null);
  const kp = [
    kcard({ ico: "compass", color: "var(--accent)", l: "Índice de vida", v: `${R.indice ?? "–"}<small>/100</small>`, dl: delta(R.indiceRaw, cmpBase(h => h.indiceRaw), { fmt: v => num(v, 1), unit: " pts" }), sp: spark(idx, "var(--accent)", { min: 0, max: 100 }), go: "roda", hero: true, sub: R.percep != null ? `você se dá ${num(R.percep)} na Roda` : "" }),
    kcard({ ico: "coins", color: acol("Finanças"), l: "Taxa de poupança", v: pct(R.fin.taxa), tgt: `meta ${pct(C.metaPoup)}`, dl: pctDelta(R.fin.taxa, cmpBase(h => h.fin.taxa)), sp: spark(H.map(h => h.fin.taxa), acol("Finanças")), go: "fin" }),
    kcard({ ico: "mood", color: acol("Saúde mental"), l: "Humor médio", v: R.humor == null ? "–" : `${num(R.humor)}<small>/5</small>`, dl: delta(R.humor, cmpBase(h => h.humor)), sp: spark(H.map(h => h.humor), acol("Saúde mental"), { min: 1, max: 5 }), go: "saude" }),
    kcard({ ico: "repeat", color: acol("Saúde física"), l: "Hábitos", v: pct(R.habMeta), tgt: "da meta", dl: pctDelta(R.habMeta, cmpBase(h => h.habMeta)), sp: spark(H.map(h => h.habMeta), acol("Saúde física"), { min: 0, max: 1 }), go: "hab" }),
    kcard({ ico: "target", color: acol("Carreira"), l: "Metas no ritmo", v: `${R.metasRitmo}<small>/${R.metasAnd}</small>`, sub: R.metasAtras ? `<span class="st-crit">${R.metasAtras} em risco</span>` : "nenhuma em risco", tgt: `progresso médio ${pct(R.metasProg)}`, go: "metas" }),
    kcard({ ico: "users", color: acol("Amizades & social"), l: "Relações em dia", v: pct(R.relEmDia), sub: R.relAtras ? `<span class="st-crit">${plural(R.relAtras, "pessoa atrasada", "pessoas atrasadas")}</span>` : "ninguém esquecido", dl: delta(R.contMes.length, cmpBase(h => h.contMes.length), { fmt: v => num(v, 0) + " contatos" }), sp: spark(H.map(h => h.contMes.length), acol("Amizades & social")), go: "pessoas" }),
  ];
  const series = [{ name: "Índice de vida", color: "var(--accent)", data: idx, proj: linProj(idx, 2).map(v => clamp(v, 0, 100)), width: 3, fillOp: .32 }];
  for (const a of AREAS) { const d = H.map(h => { const v = h.areas.find(x => x.a === a).dados; return v == null ? null : v * 10; }); if (!d.some(isNum)) continue; const on = f.area === a; series.push({ name: ashort(a), color: acol(a), data: d, fill: on, width: on ? 2.6 : 1.2, faded: !!f.area && !on, op: f.area ? null : .5, noLegend: !on, dots: on, fmt: v => num(v / 10) + "/10" }); }
  const B = calcAt(addMonth(REF, CMP === "ano" ? -12 : -1)), sB = sum(B.areas.map(a => a.contrib)), sR = sum(R.areas.map(a => a.contrib));
  const dl = R.areas.map((a, i) => ({ a: a.a, v: a.contrib - B.areas[i].contrib, d0: B.areas[i].dados, d1: a.dados })).filter(x => Math.abs(x.v) >= .05).sort((x, y) => y.v - x.v);
  const wf = sB || sR ? `<div class="wfsum"><span>${mabbr(B.mk)}</span><b>${num(sB, 1)}</b><span>→ ${mabbr(R.mk)}</span><b>${num(sR, 1)}</b><span class="dl ${sR >= sB ? "good" : "crit"}">${sgn(sR - sB, v => num(v, 1))} pts</span></div>` + diverge(dl.map(x => ({ l: ashort(x.a), v: x.v, sub: `placar ${x.d0 == null ? "–" : num(x.d0)} → ${x.d1 == null ? "–" : num(x.d1)}`, go: `data-xf="area|${esc(x.a)}"` })), { fmt: v => sgn(v, z => num(z, 1)), empty: "Nenhuma área mudou de forma relevante." }) : emptyChart();
  const P = calcAt(addMonth(REF, -1));
  const rows = R.areas.map((a, i) => ({ ...a, pv: P.areas[i].dados, ser: H.map(h => h.areas[i].dados) }));
  const tbl = `<div class="hscroll"><table class="dt sc"><thead><tr><th>Área</th><th class="num">Dados</th><th class="num">vs ant.</th><th class="num opt">Sente</th><th class="num opt">Alvo</th><th class="opt2">Tendência</th><th class="num opt">Peso</th><th><span class="sr">Mentor</span></th></tr></thead><tbody>${rows.map(a => `<tr class="click${f.area === a.a ? " sel" : ""}${f.area && f.area !== a.a ? " dim" : ""}" data-xf="area|${esc(a.a)}" tabindex="0"><td>${areaDot(a.a)}${esc(ashort(a.a))}</td><td class="num"><span class="sbar st-${a.st}" style="--v:${(a.dados ?? 0) * 10}%;--c:${acol(a.a)}">${a.dados == null ? "–" : num(a.dados)}</span></td><td class="num">${isNum(a.dados) && isNum(a.pv) ? `<span class="${a.dados >= a.pv ? "st-good" : "st-crit"}">${sgn(a.dados - a.pv)}</span>` : "–"}</td><td class="num opt">${a.perc ?? "–"}</td><td class="num opt">${a.alvo ?? "–"}</td><td class="opt2 sparkc">${spark(a.ser, acol(a.a), { min: 0, max: 10, w: 90, h: 24 })}</td><td class="num opt">${apeso(a.a)}×</td><td><a class="iconbtn sm" href="#mentor.${AREA_INFO[a.a].id}" title="Mentor de ${esc(ashort(a.a))}" aria-label="Mentor de ${esc(ashort(a.a))}">${ic("spark")}</a></td></tr>`).join("")}</tbody></table></div>`;
  const mAnd = R.metas.filter(m => m.ativa && m.rt !== "Concluída" && (!f.area || m.area === f.area)).sort((a, b) => (a.prazo || "9").localeCompare(b.prazo || "9")).slice(0, 8);
  const inf = influencers("bem", { days: PER * 30, min: 20 }).filter(i => !i.k.startsWith("t:") || i.n >= 20).slice(0, 8);
  const body = `${vis("ov-idx", "Índice de vida e áreas", lineChart(L, series, { w: vw(8), h: 270, min: 0, max: 100, proj: 2, projLabels: projLabels(2), keys: K, click: "ref", hi: K.indexOf(REF), fmt: v => num(v, 0) }), { cls: "s8", sub: f.area ? `destaque: ${ashort(f.area)} (placar × 10)` : `${PER} meses + tendência · toque num mês para analisá-lo`, info: "Índice = média ponderada dos placares de dados das áreas × 10. As linhas finas são as áreas; filtre uma área para destacá-la.", table: () => ({ cols: [{ l: "Mês" }, ...series.map(s => ({ l: s.name, num: true, f: v => v == null ? "" : num(v) }))], rows: K.map((k, i) => [mlabel(k), ...series.map(s => s.data[i])]) }) })}
    ${vis("ov-wf", "O que mudou no índice", wf, { cls: "s4", sub: `pontos que cada área somou ou tirou · toque para filtrar`, info: "Quanto cada área somou ou tirou do índice em relação ao mês de comparação, já considerando o peso da área.", table: () => ({ cols: [{ l: "Área" }, { l: "Variação (pts)", num: true, f: v => num(v, 2) }, { l: "Placar antes", num: true }, { l: "Placar agora", num: true }], rows: dl.map(x => [x.a, x.v, x.d0, x.d1]) }) })}
    ${vis("ov-mat", "Matriz das áreas", heat(AREAS.map(a => ({ l: ashort(a), key: a, color: acol(a) })), L, (i, j) => H[j].areas[i].dados, { xf: "area", sel: f.area }), { cls: "s7", sub: "placar de dados por mês · toque numa área para filtrar o relatório", table: () => ({ cols: [{ l: "Área" }, ...L.map(l => ({ l, num: true, f: v => v == null ? "" : num(v) }))], rows: AREAS.map((a, i) => [a, ...H.map(h => h.areas[i].dados)]) }) })}
    ${vis("ov-radar", "Roda: sente × dados × alvo", radar(R.areas), { cls: "s5", sub: mlabel(R.mk) })}
    ${vis("ov-sc", "Placar por área", tbl, { cls: "s7", sub: "condicional por cor · toque numa linha para filtrar", table: () => ({ cols: [{ l: "Área" }, { l: "Dados", num: true }, { l: "Mês anterior", num: true }, { l: "Percepção", num: true }, { l: "Alvo", num: true }, { l: "Peso", num: true }], rows: rows.map(a => [a.a, a.dados, a.pv, a.perc, a.alvo, apeso(a.a)]) }) })}
    ${vis("ov-metas", "Metas · progresso × tempo", mAnd.length ? `<div class="bud">${mAnd.map(m => `<div class="br click" data-ent="meta|${m.id}" role="button" tabindex="0" ${tip(`${m.meta}\nProgresso ${pct(m.prog)} · esperado ${pct(m.esp)}\n${m.rt}`)}><span>${areaDot(m.area)}${esc(m.meta)}</span><div class="bt"><i class="${m.st}" style="width:${m.prog * 100}%"></i>${m.esp != null ? `<b style="left:${m.esp * 100}%"></b>` : ""}</div><em class="${m.st}">${esc(m.rt)}</em></div>`).join("")}</div>` : emptyChart("Sem metas em andamento."), { cls: "s5", sub: f.area ? ashort(f.area) : "a marca é onde deveria estar hoje" })}
    ${vis("ov-ag", "Próximos 14 dias", agenda(R, 14, 12), { cls: "s6", sub: "tarefas, aniversários, documentos, rotinas e passos dos mentores" })}
    ${vis("ov-inf", "O que acompanha o seu humor", diverge(inf.map(i => ({ l: i.l, v: i.r, sub: i.groups ? `${i.groups.bin ? "com" : "alto"} ${num(i.groups.a)} × ${i.groups.bin ? "sem" : "baixo"} ${num(i.groups.b)} · ${i.n} dias` : `${i.n} dias`, go: `data-cx="${i.k}|bem"` })), { fmt: v => "r " + num(v, 2), max: 1 }), { cls: "s6", sub: `correlação com o humor do dia · ${PER * 30} dias · toque para cruzar`, info: "r vai de −1 a 1. Valores perto de zero indicam pouca relação. Correlação não prova causa.", table: () => ({ cols: [{ l: "Métrica" }, { l: "r", num: true, f: v => num(v, 2) }, { l: "Dias", num: true }], rows: inf.map(i => [i.l, i.r, i.n]) }) })}
    ${vis("ov-28", "Últimos 28 dias", `<div class="mt">Humor</div>${strip(R.days28, "humor", "div")}<div class="mt" style="margin-top:12px">Hábitos cumpridos</div>${strip(R.days28, "hab", "seq")}<div class="minis">${kmini(acol("Saúde física"), "Sono", R.sono == null ? "–" : num(R.sono) + " h", delta(R.sono, cmpBase(h => h.sono), { unit: " h", txt: false }))}${kmini(acol("Saúde física"), "Treinos", R.treinos, delta(R.treinos, cmpBase(h => h.treinos), { fmt: v => num(v, 0), txt: false }))}${kmini(acol("Aprendizado"), "Estudo", num(R.horasEst) + " h", delta(R.horasEst, cmpBase(h => h.horasEst), { unit: " h", txt: false }))}${kmini("var(--accent)", "Diário", plural(R.diaN, "entrada", "entradas"), R.diaHumor ? `humor ${num(R.diaHumor)}` : "")}</div>`, { cls: "s12", sub: "faixas diárias · cada quadrado é um dia" })}`;
  return reportPage(R, H, kp, body, null);
}

/* ---------------------------------------------------------------- Finanças */
function rFin(R) {
  const H = history(PER), L = H.map(h => mabbr(h.mk)), K = H.map(h => h.mk), f = xf(), F = R.fin, C = S.cfg;
  const inF = l => (!f.cat || l.cat === f.cat) && (!f.grp || (CAT_DESP[l.cat] || "Estilo de vida") === f.grp);
  const kp = [
    kcard({ ico: "coins", color: acol("Finanças"), l: "Receitas", v: eurK(F.rec), dl: delta(F.rec, cmpBase(h => h.fin.rec), { fmt: eurK }), sp: spark(H.map(h => h.fin.rec), acol("Finanças")) }),
    kcard({ ico: "download", color: GCOL["Estilo de vida"], l: "Despesas", v: eurK(F.desp), tgt: R.orcTot ? `${pct(F.desp / R.orcTot)} do orçamento` : "", dl: delta(F.desp, cmpBase(h => h.fin.desp), { up: false, fmt: eurK }), sp: spark(H.map(h => h.fin.desp), GCOL["Estilo de vida"]) }),
    kcard({ ico: "scatter", color: "var(--accent)", l: "Resultado", v: eurK(F.res), sub: `aportes ${eurK(F.apo)}`, dl: delta(F.res, cmpBase(h => h.fin.res), { fmt: eurK }), sp: spark(H.map(h => h.fin.res), "var(--accent)") }),
    kcard({ ico: "target", color: GCOL["Poupança"], l: "Taxa de poupança", v: pct(F.taxa), tgt: `meta ${pct(C.metaPoup)}`, dl: pctDelta(F.taxa, cmpBase(h => h.fin.taxa)), sp: spark(H.map(h => h.fin.taxa), GCOL["Poupança"]) }),
    kcard({ ico: "box", color: acol("Casa & organização"), l: "Reserva", v: R.reserva == null ? "–" : `${num(R.reserva)}<small> meses</small>`, tgt: `meta ${C.metaReserva}`, sp: spark(H.map(h => h.reserva), acol("Casa & organização")) }),
    kcard({ ico: "compass", color: acol("Aprendizado"), l: "Patrimônio líquido", v: eurK(R.pl), dl: delta(R.pl, cmpBase(h => h.pl), { fmt: eurK }), sp: spark(H.map(h => h.pl), acol("Aprendizado")), sub: R.plMes ? `fechado em ${mabbr(R.plMes)}` : "preencha em Orçamento" }),
  ];
  const grpData = g => H.map(h => f.cat ? (CAT_DESP[f.cat] === g ? h.fin.cat[f.cat] || 0 : 0) : f.grp && f.grp !== g ? 0 : h.fin.grp[g] || 0);
  const cols = colChart(L, GRUPOS.map(g => ({ name: g, color: GCOL[g], data: grpData(g) })), { stacked: true, w: vw(8), h: 260, fmt: eurK, keys: K, click: "ref", sel: R.mk, line: f.cat || f.grp ? [] : [{ name: "Receita", color: GCOL["Poupança"], data: H.map(h => h.fin.rec), fmt: eurK }, { name: "Resultado", color: "var(--accent)", data: H.map(h => h.fin.res), dash: true, fmt: eurK }], target: f.cat && S.orc[f.cat] ? +S.orc[f.cat] : null, targetLabel: "orçamento" });
  const wf = F.rec || F.desp ? waterfallH([{ l: "Receita", v: F.rec, total: true, color: GCOL["Poupança"] }, ...GRUPOS.map(g => ({ l: g, v: -(F.grp[g] || 0), color: GCOL[g] })), { l: "Aportes", v: -F.apo, color: "var(--a-pro)" }, { l: "Sobra em caixa", v: F.rec - F.desp - F.apo, total: true }]) + `<p class="note">${ic("info")}Da receita de ${eur(F.rec)}, ${F.rec ? pct((F.grp["Essencial"] || 0) / F.rec) : "–"} foi para o essencial, ${F.rec ? pct((F.grp["Estilo de vida"] || 0) / F.rec) : "–"} para estilo de vida e ${F.rec ? pct(F.apo / F.rec) : "–"} para aportes.</p>` : emptyChart("Sem receitas ou despesas no mês.");
  const cats = Object.entries(F.cat).map(([c, v]) => ({ l: c, v, color: GCOL[CAT_DESP[c] || "Estilo de vida"], key: c, sub: CAT_DESP[c] }));
  const bul = R.orcCats.filter(c => c.plan || c.real).sort((a, b) => (b.p ?? 0) - (a.p ?? 0)).map(c => ({ l: c.cat, real: c.real, plan: c.plan, pace: R.ritmo, st: c.st, key: c.cat }));
  const mk = R.mk, n = dim(mk), days = Array.from({ length: n }, (_, i) => `${mk}-${pad(i + 1)}`), pm = addMonth(mk, -1);
  const dsp = d => sum(S.lanc.filter(l => l.data === d && l.tipo === "Despesa" && inF(l)).map(l => l.valor));
  let acc = 0; const cum = days.map(d => d > TODAY ? null : (acc += dsp(d))); acc = 0; const cumP = days.map((_, i) => i < dim(pm) ? (acc += dsp(`${pm}-${pad(i + 1)}`)) : null);
  const orc = f.cat ? +S.orc[f.cat] || 0 : f.grp ? sum(Object.entries(S.orc).filter(([c]) => CAT_DESP[c] === f.grp).map(([, v]) => +v)) : R.orcTot;
  const dmap = {}; days.forEach(d => { const v = dsp(d); if (v) dmap[d] = v; });
  const top = R.lm.filter(l => l.tipo === "Despesa" && inF(l)).sort((a, b) => b.valor - a.valor), mx = Math.max(1, ...top.map(l => +l.valor));
  const pk = Object.keys(S.patr).filter(k => k <= mk).sort().slice(-12), pv = k => S.patr[k] || {};
  const body = `${finTermometro("s12")}
    ${vis("fin-cols", "Despesas por grupo, receita e resultado", cols, { cls: "s8", sub: `${PER} meses · toque num mês para analisá-lo${f.cat ? ` · filtro: ${f.cat}` : ""}`, table: () => ({ cols: [{ l: "Mês" }, { l: "Receita", num: true, f: v => eur(v) }, ...GRUPOS.map(g => ({ l: g, num: true, f: v => eur(v) })), { l: "Aportes", num: true, f: v => eur(v) }, { l: "Resultado", num: true, f: v => eur(v) }], rows: H.map(h => [mlabel(h.mk), h.fin.rec, ...GRUPOS.map(g => h.fin.grp[g] || 0), h.fin.apo, h.fin.res]) }) })}
    ${vis("fin-wf", "Cascata do mês", wf, { cls: "s4", sub: `${mlabel(mk)} · da receita à sobra` })}
    ${vis("fin-sk", "Para onde foi o dinheiro", sankey(F), { cls: "s6", sub: "receita → grupos → categorias · toque numa categoria para filtrar" })}
    ${vis("fin-tm", "Mapa das categorias", treemap(cats, { w: vw(6), h: 300, xf: "cat", sel: f.cat }), { cls: "s6", sub: "área proporcional ao gasto · toque para filtrar", table: () => ({ cols: [{ l: "Categoria" }, { l: "Grupo" }, { l: "Valor", num: true, f: v => eur(v, 2) }, { l: "% das despesas", num: true, f: v => pct(v, 1) }], rows: cats.sort((a, b) => b.v - a.v).map(c => [c.l, c.sub, c.v, F.desp ? c.v / F.desp : null]) }) })}
    ${vis("fin-bul", "Orçamento × real", bullet(bul, { xf: "cat", sel: f.cat }), { cls: "s6", sub: `barra = real · traço = orçamento · pontilhado = ritmo (${pct(R.ritmo)} do mês)`, act: `<a class="lnk" href="#fin.orc">Editar orçamento</a>`, table: () => ({ cols: [{ l: "Categoria" }, { l: "Real", num: true, f: v => eur(v, 2) }, { l: "Orçamento", num: true, f: v => v ? eur(v, 2) : "" }, { l: "Uso", num: true, f: v => v == null ? "" : pct(v) }], rows: R.orcCats.map(c => [c.cat, c.real, c.plan, c.p]) }) })}
    ${vis("fin-cum", "Gasto acumulado no mês", lineChart(days.map((_, i) => String(i + 1)), [{ name: "Este mês", color: GCOL["Estilo de vida"], data: cum }, { name: "Mês anterior", color: "var(--muted)", data: cumP, fill: false, dash: true, dots: false }, ...(orc ? [{ name: "Ritmo do orçamento", color: "var(--warn)", data: days.map((_, i) => orc * (i + 1) / n), fill: false, dash: true, dots: false }] : [])], { w: vw(6), h: 250, fmt: eurK, maxLabels: 10 }), { cls: "s6", sub: `${mlabel(mk)}${f.cat ? " · " + f.cat : f.grp ? " · " + f.grp : ""}${R.proj != null && !f.cat && !f.grp ? ` · projeção ${eur(R.proj)}` : ""}` })}
    ${vis("fin-cal", "Calendário de gastos", calMonth(mk, dmap, { fmt: v => eur(v), zero: "sem gastos" }), { cls: "s6", sub: `cor mais forte = dia mais caro${f.cat ? " · " + f.cat : ""}` })}
    ${vis("fin-top", "Maiores despesas do mês", top.length ? `<div class="hscroll"><table class="dt"><thead><tr><th>Descrição</th><th>Categoria</th><th class="num opt">Dia</th><th class="num">Valor</th><th class="opt" style="min-width:110px">Peso</th></tr></thead><tbody>${top.slice(0, 12).map(d => `<tr class="click" data-edit="lanc" data-id="${d.id}" tabindex="0"><td>${esc(d.desc || "—")}${d.origem === "diário" ? ` <span class="chip xs">diário</span>` : ""}</td><td><button type="button" class="gtag" style="--c:${GCOL[CAT_DESP[d.cat] || "Estilo de vida"]}" data-xf="cat|${esc(d.cat)}">${esc(d.cat)}</button></td><td class="num opt">${fmtD(d.data)}</td><td class="num"><span class="vcell" style="--a:${Math.round(+d.valor / mx * 50)}%">${eur(+d.valor, 2)}</span></td><td class="opt"><div class="mbar"><i style="width:${+d.valor / mx * 100}%"></i></div></td></tr>`).join("")}</tbody><tfoot><tr><td colspan="3">${plural(top.length, "despesa", "despesas")}</td><td class="num"><b>${eur(sum(top.map(l => +l.valor)), 2)}</b></td><td class="opt"></td></tr></tfoot></table></div>` : emptyChart("Sem despesas com esses filtros."), { cls: "s6", sub: "toque para editar · toque na categoria para filtrar", table: () => ({ cols: [{ l: "Data" }, { l: "Descrição" }, { l: "Categoria" }, { l: "Valor", num: true, f: v => eur(v, 2) }], rows: top.map(l => [l.data, l.desc, l.cat, +l.valor]) }) })}
    ${vis("fin-pl", "Patrimônio", pk.length >= 2 ? lineChart(pk.map(mabbr), [{ name: "Patrimônio líquido", color: "var(--accent)", data: pk.map(k => (+pv(k).contas || 0) + (+pv(k).reserva || 0) + (+pv(k).invest || 0) + (+pv(k).outros || 0) - (+pv(k).dividas || 0)), width: 3 }, { name: "Reserva", color: GCOL["Poupança"], data: pk.map(k => +pv(k).reserva || 0), fill: false }, { name: "Investimentos", color: acol("Aprendizado"), data: pk.map(k => +pv(k).invest || 0), fill: false }, { name: "Dívidas", color: "var(--crit)", data: pk.map(k => +pv(k).dividas || 0), fill: false, dash: true }], { w: vw(6), h: 250, fmt: eurK }) : emptyChart("Preencha o patrimônio de pelo menos dois meses em Finanças › Orçamento & patrimônio."), { cls: "s6", sub: "fim de cada mês" })}
    ${vis("fin-ass", "Assinaturas", hbars(R.ass.sort((a, b) => b.mensal - a.mensal).map(a => ({ l: a.servico, v: a.mensal, color: a.uso === "Baixo" ? "var(--crit)" : a.uso === "Médio" ? "var(--warn)" : GCOL["Poupança"], sub: `uso ${a.uso.toLowerCase()} · ${a.periodo.toLowerCase()}`, txt: eur(a.mensal, 2) })), { empty: "Sem assinaturas cadastradas." }) + (R.economia ? `<p class="note">${ic("bolt")}Cancelar as de uso baixo libera <b>${eur(R.economia, 2)}/mês</b> (${eur(R.economia * 12)} por ano).</p>` : ""), { cls: "s6", sub: `${eur(R.assMes, 2)} por mês` })}`;
  return reportPage(R, H, kp, body + finExtras(R), ["Finanças"]);
}

/* ---------------------------------------------------------------- Saúde */
const HSV = { cal: "bem" };
function rSaude(R) {
  const H = history(PER), C = S.cfg, D = DAILY(), s0 = Math.max(0, D.N - 90), dts = D.dates.slice(s0), ma = k => movAvg(D.C[k].slice(s0), 7);
  const kp = [
    kcard({ ico: "clock", color: acol("Saúde física"), l: "Sono médio", v: R.sono == null ? "–" : `${num(R.sono)}<small> h</small>`, tgt: `meta ${num(C.metaSono)} h`, dl: delta(R.sono, cmpBase(h => h.sono), { unit: " h" }), sp: spark(H.map(h => h.sono), acol("Saúde física")) }),
    kcard({ ico: "mood", color: acol("Saúde mental"), l: "Humor", v: R.humor == null ? "–" : `${num(R.humor)}<small>/5</small>`, dl: delta(R.humor, cmpBase(h => h.humor)), sp: spark(H.map(h => h.humor), acol("Saúde mental"), { min: 1, max: 5 }) }),
    kcard({ ico: "bolt", color: acol("Lazer & criatividade"), l: "Energia", v: R.energia == null ? "–" : `${num(R.energia)}<small>/5</small>`, dl: delta(R.energia, cmpBase(h => h.energia)), sp: spark(H.map(h => h.energia), acol("Lazer & criatividade"), { min: 1, max: 5 }) }),
    kcard({ ico: "pulse", color: "var(--crit)", l: "Estresse", v: R.estresse == null ? "–" : `${num(R.estresse)}<small>/5</small>`, dl: delta(R.estresse, cmpBase(h => h.estresse), { up: false }), sp: spark(H.map(h => h.estresse), "var(--crit)", { min: 1, max: 5 }) }),
    kcard({ ico: "repeat", color: acol("Carreira"), l: "Treinos", v: R.treinos, tgt: `meta ${Math.round(C.metaTreinos * R.DR / 7)} até agora`, dl: delta(R.treinos, cmpBase(h => h.treinos), { fmt: v => num(v, 0) }), sp: spark(H.map(h => h.treinos), acol("Carreira")) }),
    kcard({ ico: "arrow", color: acol("Finanças"), l: "Passos/dia", v: R.passos == null ? "–" : num(R.passos, 0), tgt: `meta ${num(C.metaPassos, 0)}`, dl: delta(R.passos, cmpBase(h => h.passos), { fmt: v => num(v, 0) }), sp: spark(H.map(h => h.passos), acol("Finanças")) }),
  ];
  const trend = lineChart(dts.map(fmtD), [{ name: "Humor", color: acol("Saúde mental"), data: ma("humor") }, { name: "Energia", color: acol("Lazer & criatividade"), data: ma("energia"), fill: false }, { name: "Estresse", color: "var(--crit)", data: ma("estresse"), fill: false, dash: true }, { name: "Sono (h)", color: acol("Saúde física"), data: ma("sono"), right: true, fill: false, width: 2.6 }], { w: vw(8), h: 270, min: 1, max: 5, right: { min: 4, max: 9, fmt: v => num(v, 0) + " h" }, fmt: v => num(v, 0), maxLabels: 9, dots: false });
  const calK = { bem: ["Humor", 1, 5, "div"], sono: ["Sono", 4.5, 9, "seq"], passos: ["Passos", null, null, "seq"], treino: ["Treinou", 0, 1, "seq"], hab: ["Hábitos", 0, 1, "seq"] }[HSV.cal];
  const map = {}; D.dates.forEach((d, i) => { const v = D.C[HSV.cal]?.[i]; if (isNum(v)) map[d] = v; });
  const sp = []; for (let i = Math.max(0, D.N - PER * 30); i < D.N; i++) if (isNum(D.C.sono[i]) && isNum(D.C.humor[i])) sp.push({ x: D.C.sono[i], y: D.C.humor[i], d: D.dates[i] });
  const cr = crossData("sono", "humor", { days: PER * 30 });
  const wdv = k => [1, 2, 3, 4, 5, 6, 0].map(w => avg(D.dates.map((d, i) => i >= D.N - PER * 30 && parse(d).getDay() === w ? D.C[k][i] : null)));
  const tr = {}; Object.entries(S.saude).filter(([d, e]) => e.treino && d >= addDays(TODAY, -PER * 30)).forEach(([, e]) => { tr[e.treino] = (tr[e.treino] || 0) + 1; });
  const pal = ["var(--a-fis)", "var(--a-car)", "var(--a-fin)", "var(--a-apr)", "var(--a-laz)", "var(--a-men)", "var(--a-fam)", "var(--a-ami)"];
  const ws = Object.entries(S.saude).filter(([, e]) => isNum(e.peso)).sort(), mp = S.metas.find(m => m.un === "kg" && m.ativa !== false && isNum(m.alvo));
  let wch = emptyChart("Registre o peso no check-in para ver a tendência.");
  if (ws.length >= 3) { const lab = ws.map(([d]) => fmtD(d)), vals = ws.map(([, e]) => +e.peso), f = regress(ws.map(([d, e]) => ({ x: diff(d, ws[0][0]), y: +e.peso })));
    const proj = f && mp?.prazo && mp.prazo > TODAY ? [Math.round((f.a + f.b * diff(mp.prazo, ws[0][0])) * 10) / 10] : [];
    wch = lineChart(lab, [{ name: "Peso", color: acol("Saúde física"), data: vals, proj }], { w: vw(6), h: 240, zero: false, target: mp ? +mp.alvo : null, targetLabel: mp ? `meta ${mp.alvo} kg` : "", proj: proj.length, projLabels: proj.length ? [fmtD(mp.prazo)] : [], fmt: v => num(v, 1), maxLabels: 8 }) + (proj.length ? `<p class="note">No ritmo atual você chega a <b>${num(proj[0])} kg</b> em ${fmtDY(mp.prazo)} (meta ${num(+mp.alvo)} kg).</p>` : ""); }
  const steps = aggSeries("passos", "w", 16);
  const body = `${vis("sa-tr", "Humor, energia, estresse e sono", trend, { cls: "s8", sub: "média móvel de 7 dias · últimos 90 dias · sono no eixo da direita", table: () => ({ cols: [{ l: "Dia" }, { l: "Humor", num: true }, { l: "Energia", num: true }, { l: "Estresse", num: true }, { l: "Sono", num: true }], rows: dts.map((d, i) => [d, D.C.humor[s0 + i], D.C.energia[s0 + i], D.C.estresse[s0 + i], D.C.sono[s0 + i]]) }) })}
    ${vis("sa-sc", "Sono × humor", scatter(sp, { w: vw(4), h: 270, xl: "Sono (h)", yl: "Humor", jitter: [.12, .35], yr: [1, 5], fit: true, color: acol("Saúde mental"), op: .45 }) + (cr?.r != null ? `<p class="note">Correlação ${rWord(cr.r)} (r = ${num(cr.r, 2)}, ${cr.n} dias)${cr.fit ? ` · cada hora a mais de sono ≈ ${sgn(cr.fit.b, v => num(v, 2))} no humor` : ""}.</p>` : ""), { cls: "s4", sub: `${PER * 30} dias · cada ponto é um dia`, act: `<button type="button" class="lnk" data-cx="sono|humor">Abrir no explorador</button>` })}
    ${vis("sa-cal", `Ano em ${calK[0].toLowerCase()}`, `<div class="segs">${[["bem", "Humor"], ["sono", "Sono"], ["passos", "Passos"], ["treino", "Treinos"], ["hab", "Hábitos"]].map(([k, l]) => `<button type="button" class="seg" data-hscal="${k}" aria-pressed="${HSV.cal === k}">${l}</button>`).join("")}</div>${calYear(map, { mode: calK[3], min: calK[1] ?? undefined, max: calK[2] ?? undefined, fmt: v => HSV.cal === "treino" ? (v ? "treinou" : "sem treino") : HSV.cal === "hab" ? pct(v) + " dos hábitos" : HSV.cal === "passos" ? num(v, 0) + " passos" : HSV.cal === "sono" ? num(v) + " h" : "humor " + num(v), color: HSV.cal === "sono" ? acol("Saúde física") : HSV.cal === "passos" ? acol("Finanças") : "var(--accent)", click: "dday" })}`, { cls: "s12", sub: "últimas 53 semanas · toque num dia para abrir o diário daquela data" })}
    ${vis("sa-wd", "Perfil da semana", colChart(["Seg", "Ter", "Qua", "Qui", "Sex", "Sáb", "Dom"], [{ name: "Humor", color: acol("Saúde mental"), data: wdv("bem") }, { name: "Energia", color: acol("Lazer & criatividade"), data: wdv("energia") }, { name: "Estresse", color: "var(--crit)", data: wdv("estresse") }], { w: vw(4), h: 230, fmt: v => num(v, 1) }), { cls: "s4", sub: `média por dia da semana · ${PER * 30} dias` })}
    ${vis("sa-trn", "Treinos por tipo", donut(Object.entries(tr).sort((a, b) => b[1] - a[1]).map(([l, v], i) => ({ l, v, color: pal[i % pal.length] })), String(sum(Object.values(tr))), "treinos", { fmt: v => plural(v, "treino", "treinos") }), { cls: "s4", sub: `${PER * 30} dias` })}
    ${vis("sa-hist", "Distribuição do sono", hist(D.C.sono.slice(Math.max(0, D.N - PER * 30)), { bins: 9, min: 4.5, max: 9, color: acol("Saúde física"), name: "Noites", fmt: v => num(v, 1) + " h", h: 230, w: vw(4), maxLabels: 5 }), { cls: "s4", sub: `noites por faixa de horas · meta ${num(C.metaSono)} h` })}
    ${vis("sa-peso", "Peso", wch, { cls: "s6", sub: mp ? `meta: ${esc(mp.meta)}` : "registros semanais" })}
    ${vis("sa-steps", "Passos por semana", colChart(steps.labels, [{ name: "Passos/dia", color: acol("Finanças"), data: steps.vals }], { w: vw(6), h: 240, target: C.metaPassos, targetLabel: "meta", legend: false, fmt: v => num(v, 0) }), { cls: "s6", sub: "média diária de cada semana · 16 semanas" })}`;
  return reportPage(R, H, kp, body, ["Saúde física", "Saúde mental"]);
}

/* ---------------------------------------------------------------- Hábitos */
function bestStreak(id) { let best = 0, cur = 0; const ds = Object.keys(S.marks).filter(k => k.startsWith(id + "|")).map(k => k.split("|")[1]).sort(); let prev = null; for (const d of ds) { cur = prev && diff(d, prev) === 1 ? cur + 1 : 1; best = Math.max(best, cur); prev = d; } return best; }
function rHab(R) {
  const H = history(PER), f = xf(), D = DAILY(), habs = R.hab.filter(h => !f.area || h.area === f.area), W = 16, wk0 = addDays(weekStart(TODAY), -7 * (W - 1));
  const perfect = Array.from({ length: R.DR }, (_, i) => `${R.mk}-${pad(i + 1)}`).filter(d => S.habitos.length && S.habitos.every(h => S.marks[`${h.id}|${d}`])).length;
  const kp = [
    kcard({ ico: "repeat", color: acol("Saúde física"), l: "% da meta (média)", v: pct(R.habMeta), dl: pctDelta(R.habMeta, cmpBase(h => h.habMeta)), sp: spark(H.map(h => h.habMeta), acol("Saúde física"), { min: 0, max: 1 }) }),
    kcard({ ico: "check", color: acol("Finanças"), l: "Feitos no mês", v: sum(R.hab.map(h => h.feitos)), dl: delta(sum(R.hab.map(h => h.feitos)), cmpBase(h => sum(h.hab.map(x => x.feitos))), { fmt: v => num(v, 0) }), sp: spark(H.map(h => sum(h.hab.map(x => x.feitos))), acol("Finanças")) }),
    kcard({ ico: "bolt", color: acol("Família"), l: "Maior sequência atual", v: R.hab.length ? `${Math.max(...R.hab.map(h => h.streak))}<small> dias</small>` : "–", sub: R.hab.length ? esc([...R.hab].sort((a, b) => b.streak - a.streak)[0].nome) : "" }),
    kcard({ ico: "spark", color: "var(--accent)", l: "Dias perfeitos", v: perfect, sub: "todos os hábitos feitos no mês" }),
    kcard({ ico: "info", color: "var(--crit)", l: "Abaixo da meta", v: R.hab.filter(h => h.st === "crit").length, sub: "menos de 60% da meta" }),
  ];
  const wkCell = (h, w) => { const s = addDays(wk0, w * 7); let n = 0; for (let k = 0; k < 7; k++) if (S.marks[`${h.id}|${addDays(s, k)}`]) n++; const lim = Math.min(7, diff(TODAY, s) + 1); return lim <= 0 ? null : Math.min(1, n / Math.max(.1, h.meta * lim / 7)); };
  const grid = `<div class="hscroll"><div class="heat seq" style="grid-template-columns:minmax(120px,180px) repeat(${W},minmax(20px,1fr));min-width:${120 + W * 23}px"><div></div>${Array.from({ length: W }, (_, w) => `<div class="hh">${w % 2 ? "" : fmtD(addDays(wk0, w * 7))}</div>`).join("")}${habs.map(h => `<button type="button" class="hr${f.hab === h.id ? " sel" : ""}" data-xf="hab|${h.id}"><i style="background:${acol(h.area)}"></i>${esc(h.nome)}</button>${Array.from({ length: W }, (_, w) => { const v = wkCell(h, w); return `<div class="hc${f.hab && f.hab !== h.id ? " dim" : ""}" style="background:${v == null ? "var(--cell)" : `color-mix(in srgb, ${acol(h.area)} ${Math.round(10 + v * 85)}%, var(--cell))`}" ${tip(`${h.nome} · semana de ${fmtD(addDays(wk0, w * 7))}: ${v == null ? "–" : pct(v)} da meta`)}></div>`; }).join("")}`).join("")}</div></div>`;
  const imp = R.hab.map(h => ({ h, c: crossData("h:" + h.id, "bem", { days: PER * 30 }) })).filter(x => x.c?.groups?.bin).map(x => ({ l: x.h.nome, v: x.c.groups.a - x.c.groups.b, sub: `com ${num(x.c.groups.a)} × sem ${num(x.c.groups.b)} · ${x.c.n} dias`, go: `data-xf="hab|${x.h.id}"` })).sort((a, b) => b.v - a.v);
  const imp2 = R.hab.map(h => ({ h, c: crossData("h:" + h.id, "estresse", { days: PER * 30 }) })).filter(x => x.c?.groups?.bin).map(x => ({ l: x.h.nome, v: x.c.groups.b - x.c.groups.a, sub: `estresse com ${num(x.c.groups.a)} × sem ${num(x.c.groups.b)}`, go: `data-xf="hab|${x.h.id}"` })).sort((a, b) => b.v - a.v);
  const mdays = Array.from({ length: dim(R.mk) }, (_, i) => `${R.mk}-${pad(i + 1)}`);
  const cal = habs.length ? `<div class="hscroll"><div class="cal" style="grid-template-columns:minmax(120px,1.4fr) repeat(${mdays.length},minmax(10px,1fr)) 46px">${habs.map(h => `<div class="cn">${esc(h.nome)}</div>${mdays.map(d => `<div class="cd${S.marks[h.id + "|" + d] ? " on" : d > TODAY ? " fut" : ""}" style="--c:${acol(h.area)}" ${tip(`${h.nome} · ${fmtDL(d)}`)}></div>`).join("")}<div class="cp st-${h.st}">${pct(h.pm)}</div>`).join("")}</div></div>` : emptyChart("Nenhum hábito.");
  const wdHeat = `<div class="hscroll"><div class="heat seq" style="grid-template-columns:minmax(120px,180px) repeat(7,minmax(36px,1fr));min-width:${120 + 7 * 39}px"><div></div>${["Seg", "Ter", "Qua", "Qui", "Sex", "Sáb", "Dom"].map(x => `<div class="hh">${x}</div>`).join("")}${habs.map(h => `<div class="hr static"><i style="background:${acol(h.area)}"></i>${esc(h.nome)}</div>${[1, 2, 3, 4, 5, 6, 0].map(w => { const v = avg(D.dates.map((d, i) => i >= D.N - PER * 30 && parse(d).getDay() === w ? D.C["h:" + h.id]?.[i] : null)); return `<div class="hc" style="background:${v == null ? "var(--cell)" : `color-mix(in srgb, ${acol(h.area)} ${Math.round(8 + v * 88)}%, var(--cell))`}" ${tip(`${h.nome} · ${DOWL[w]}: ${pct(v)} dos dias`)}>${v == null ? "" : pct(v)}</div>`; }).join("")}`).join("")}</div></div>`;
  const sel = f.hab ? S.habitos.find(h => h.id === f.hab) : null, sw = sel ? aggSeries("h:" + sel.id, "w", 16) : null;
  const body = `${vis("hb-grid", "Consistência semana a semana", grid, { cls: "s8", sub: "% da meta semanal · 16 semanas · toque num hábito para filtrar" })}
    ${vis("hb-imp", "Impacto no humor", diverge(imp, { fmt: v => sgn(v) }), { cls: "s4", sub: "humor nos dias com o hábito − sem ele", info: "Diferença de médias; não prova causa, mas aponta onde vale insistir.", table: () => ({ cols: [{ l: "Hábito" }, { l: "Diferença", num: true, f: v => num(v, 2) }, { l: "Detalhe" }], rows: imp.map(x => [x.l, x.v, x.sub]) }) })}
    ${vis("hb-cal", `Calendário de ${mlabel(R.mk)}`, cal, { cls: "s8", sub: "cada quadrado é um dia · a porcentagem é da meta do mês até hoje", act: `<a class="lnk" href="#hab.marcar">Marcar hábitos</a>` })}
    ${vis("hb-str", "Alívio do estresse", diverge(imp2, { fmt: v => sgn(v) }), { cls: "s4", sub: "quanto o estresse cai nos dias com o hábito" })}
    ${vis("hb-wd", "Por dia da semana", wdHeat, { cls: "s7", sub: `% dos dias cumpridos · ${PER * 30} dias` })}
    ${vis("hb-seq", "Sequências", hbars(habs.map(h => ({ l: h.nome, v: bestStreak(h.id), mark: h.streak, color: acol(h.area), txt: `${h.streak} agora · recorde ${bestStreak(h.id)}` })).sort((a, b) => b.v - a.v), { fmt: v => num(v, 0) }), { cls: "s5", sub: "barra = recorde · traço = sequência atual" })}
    ${sel ? vis("hb-sel", `${esc(sel.nome)} · semana a semana`, lineChart(sw.labels, [{ name: "% dos dias", color: acol(sel.area), data: sw.vals }], { w: vw(12), h: 220, min: 0, max: 1, fmt: v => pct(v), target: Math.min(1, sel.meta / 7), targetLabel: `meta ${sel.meta}×/semana`, legend: false }), { cls: "s12", sub: "fração dos dias da semana em que o hábito foi feito" }) : ""}`;
  return reportPage(R, H, kp, body, ["Saúde física", "Saúde mental"]);
}

/* ---------------------------------------------------------------- Relações */
function proximity(R) {
  const W = 560, H = 440, cx = W / 2, cy = H / 2, rings = [106, 144, 192], ps = R.pes.filter(p => +p.freq), rels = [...new Set(ps.map(p => p.relacao))];
  if (!ps.length) return emptyChart("Cadastre pessoas com uma frequência de contato.");
  const band = ratio => ratio < .8 ? 52 + ratio / .8 * 50 : ratio <= 1 ? 108 + (ratio - .8) / .2 * 32 : 148 + Math.min(1, (ratio - 1) / 2) * 40;
  let g = [...rings].reverse().map((r, i) => `<circle cx="${cx}" cy="${cy}" r="${r}" class="ring${2 - i}"/>`).join("") + rings.map((r, i) => `<text x="${cx}" y="${cy - r + 13}" text-anchor="middle" class="ax sm">${["em dia", "em breve", "atrasado"][i]}</text>`).join("");
  g += `<circle cx="${cx}" cy="${cy}" r="26" class="me"/><text x="${cx}" y="${cy + 4}" text-anchor="middle" class="sk1">Você</text>`;
  rels.forEach((rel, ri) => { const grp = ps.filter(p => p.relacao === rel), a0 = ri / rels.length * Math.PI * 2 - Math.PI / 2, span = Math.PI * 2 / rels.length;
    const lx = cx + Math.cos(a0 + span / 2) * (rings[2] + 18), ly = cy + Math.sin(a0 + span / 2) * (rings[2] + 18) + 4;
    g += `<text x="${lx.toFixed(1)}" y="${ly.toFixed(1)}" text-anchor="${lx < cx - 10 ? "end" : lx > cx + 10 ? "start" : "middle"}" class="ax rl">${esc(rel)}</text>`;
    grp.forEach((p, k) => { const ang = a0 + span * (k + .5) / grp.length, ratio = p.ult ? clamp(p.dias / p.freq, 0, 3) : 3, r = band(ratio), x = cx + Math.cos(ang) * r, y = cy + Math.sin(ang) * r;
      const n90 = S.contatos.filter(c => c.pessoa === p.nome && c.data >= addDays(TODAY, -90)).length, rad = 6 + Math.sqrt(n90) * 2.4, col = acol(relArea(p.relacao));
      g += `<line x1="${cx}" y1="${cy}" x2="${x.toFixed(1)}" y2="${y.toFixed(1)}" class="spoke"/><g class="click" data-ent="p|${esc(p.nome)}" ${tip(`${p.nome} · ${p.relacao}\n${p.txt}${p.ult ? ` · último contato há ${p.dias} dias` : ""}\n${n90} contatos em 90 dias · falar a cada ${p.freq} dias`)}><circle cx="${x.toFixed(1)}" cy="${y.toFixed(1)}" r="${rad.toFixed(1)}" fill="${col}" class="pnode st-${p.st}"/><text x="${x.toFixed(1)}" y="${(y + rad + 12).toFixed(1)}" text-anchor="middle" class="ax pl">${esc(trunc(p.nome.replace(/\s*\(.*\)/, ""), 14))}</text></g>`; }); });
  return svgWrap(W, H, g, "Mapa de proximidade", "chart prox");
}
function rRel(R) {
  const H = history(PER), L = H.map(h => mabbr(h.mk)), K = H.map(h => h.mk), f = xf(), st = diaryStats();
  const ps = R.pes.filter(p => (!f.rel || p.relacao === f.rel) && (!f.area || relArea(p.relacao) === f.area));
  const mnt = S.diario.filter(e => mkey(e.data) === R.mk).reduce((n, e) => n + parseEntry(e.texto).people.length, 0);
  const kp = [
    kcard({ ico: "users", color: acol("Amizades & social"), l: "Em dia", v: pct(R.relEmDia), sub: "dentro da frequência desejada" }),
    kcard({ ico: "clock", color: "var(--crit)", l: "Atrasados", v: R.relAtras, sub: "passou da frequência desejada" }),
    kcard({ ico: "heart", color: acol("Amor & parceria"), l: "Contatos no mês", v: R.contMes.length, dl: delta(R.contMes.length, cmpBase(h => h.contMes.length), { fmt: v => num(v, 0) }), sp: spark(H.map(h => h.contMes.length), acol("Amor & parceria")) }),
    kcard({ ico: "spark", color: acol("Família"), l: "Qualidade média", v: R.contMes.length ? `${num(avg(R.contMes.map(c => c.qual)))}<small>/5</small>` : "–", sp: spark(H.map(h => avg(h.contMes.map(c => c.qual))), acol("Família"), { min: 1, max: 5 }) }),
    kcard({ ico: "at", color: "var(--accent)", l: "Menções no diário", v: mnt, sub: mlabel(R.mk) }),
  ];
  const rels = RELACAO.filter(r => S.contatos.some(c => S.pessoas.find(p => p.nome === c.pessoa)?.relacao === r));
  const relOf = n => S.pessoas.find(p => p.nome === n)?.relacao || "Amizade";
  const cm = colChart(L, rels.map(r => ({ name: r, color: acol(relArea(r)), data: H.map(h => h.contMes.filter(c => relOf(c.pessoa) === r).length) })), { stacked: true, w: vw(6), h: 250, keys: K, click: "ref", sel: R.mk, fmt: v => num(v, 0) });
  const fb = R.pes.map(p => ({ p, c: crossData("p:" + p.nome, "bem", { days: Math.max(180, PER * 30) }) })).filter(x => x.c?.groups?.bin && x.c.groups.na >= 3).map(x => ({ l: x.p.nome, v: x.c.groups.a - x.c.groups.b, sub: `juntos ${num(x.c.groups.a)} × outros dias ${num(x.c.groups.b)} · ${x.c.groups.na} dias juntos`, go: `data-ent="p|${esc(x.p.nome)}"` })).sort((a, b) => b.v - a.v);
  const tipos = {}; R.contMes.forEach(c => tipos[c.tipo] = (tipos[c.tipo] || 0) + 1);
  const aniv = R.pes.filter(p => p.faltam != null && p.faltam <= 60).sort((a, b) => a.faltam - b.faltam);
  const body = `${vis("rl-px", "Mapa de proximidade", proximity(R), { cls: "s6", sub: "perto do centro = em dia · tamanho = contatos em 90 dias · toque numa pessoa" })}
    ${vis("rl-at", "Quem precisa de atenção", hbars(ps.filter(p => +p.freq).sort((a, b) => b.ratio - a.ratio).map(p => ({ l: p.nome, v: Math.min(p.ratio, 3), mark: 1, color: p.st === "crit" ? "var(--crit)" : p.st === "warn" ? "var(--warn)" : acol(relArea(p.relacao)), sub: `${p.relacao} · a cada ${p.freq} dias`, txt: p.ult ? `${p.dias} d` : "nunca", st: p.st })), { max: 3, xf: "rel", fmt: v => num(v, 1) }), { cls: "s6", sub: "dias desde o último contato ÷ frequência desejada · traço = no limite", table: () => ({ cols: [{ l: "Pessoa" }, { l: "Relação" }, { l: "Dias", num: true }, { l: "Frequência", num: true }, { l: "Status" }], rows: R.pes.map(p => [p.nome, p.relacao, p.dias, p.freq, p.txt]) }) })}
    ${vis("rl-cm", "Contatos por mês", cm, { cls: "s6", sub: "por tipo de relação" })}
    ${vis("rl-fb", "Quem te faz bem", diverge(fb.slice(0, 10), { fmt: v => sgn(v) }), { cls: "s6", sub: "humor nos dias com a pessoa (contato ou diário) − nos outros dias", info: "Junta contatos registrados e menções no diário.", table: () => ({ cols: [{ l: "Pessoa" }, { l: "Diferença", num: true, f: v => num(v, 2) }, { l: "Detalhe" }], rows: fb.map(x => [x.l, x.v, x.sub]) }) })}
    ${vis("rl-tp", "Como vocês se falam", donut(Object.entries(tipos).map(([l, v], i) => ({ l, v, color: ["var(--a-ami)", "var(--a-fam)", "var(--a-car)", "var(--a-men)", "var(--a-laz)"][i % 5] })), String(R.contMes.length), "contatos", { fmt: v => plural(v, "contato", "contatos") }), { cls: "s4", sub: mlabel(R.mk) })}
    ${vis("rl-dm", "Mais citados no diário", hbars(Object.entries(st.people).sort((a, b) => b[1].n - a[1].n).slice(0, 8).map(([n, x]) => ({ l: n, v: x.n, sub: x.mood != null ? `humor ${num(x.mood)}` : "", color: acol(relArea(S.pessoas.find(p => p.nome === n)?.relacao)) })), { fmt: v => plural(v, "entrada", "entradas"), empty: "Mencione pessoas com @ no diário." }), { cls: "s4", sub: "todas as entradas" })}
    ${vis("rl-an", "Aniversários", aniv.length ? `<div class="list">${aniv.map(p => `<button type="button" class="li click" data-ent="p|${esc(p.nome)}"><div class="t">${esc(p.nome)}<div class="m">${fmtDL(p.prox)}</div></div>${pill(p.faltam <= 7 ? "warn" : "none", p.faltam === 0 ? "hoje" : `em ${p.faltam} d`)}</button>`).join("")}</div>` : emptyChart("Nenhum nos próximos 60 dias."), { cls: "s4", sub: "próximos 60 dias" })}`;
  return reportPage(R, H, kp, body, ["Família", "Amor & parceria", "Amizades & social"]);
}

/* ---------------------------------------------------------------- Crescimento */
function rCresc(R) {
  const H = history(PER), L = H.map(h => mabbr(h.mk)), K = H.map(h => h.mk), f = xf(), C = S.cfg;
  const kp = [
    kcard({ ico: "book", color: acol("Aprendizado"), l: "Estudo no mês", v: `${num(R.horasEst)}<small> h</small>`, tgt: `meta ${C.metaEstudo} h`, dl: delta(R.horasEst, cmpBase(h => h.horasEst), { unit: " h" }), sp: spark(H.map(h => h.horasEst), acol("Aprendizado")) }),
    kcard({ ico: "file", color: acol("Propósito & espiritualidade"), l: "Livros no ano", v: `${R.livros}<small>/${C.metaLivros}</small>`, sub: "concluídos" }),
    kcard({ ico: "target", color: acol("Carreira"), l: "Competências", v: pct(R.compPct), sub: "nível atual ÷ alvo" }),
    kcard({ ico: "brief", color: acol("Carreira"), l: "Candidaturas ativas", v: R.candAtivas, sub: `${S.cand.filter(c => c.dataAcao && c.dataAcao < TODAY && !["Aceito", "Recusado", "Desisti"].includes(c.etapa)).length} ação(ões) atrasada(s)` }),
    kcard({ ico: "palette", color: acol("Lazer & criatividade"), l: "Lazer no mês", v: `${num(R.horasLaz)}<small> h</small>`, dl: delta(R.horasLaz, cmpBase(h => h.horasLaz), { unit: " h" }), sp: spark(H.map(h => h.horasLaz), acol("Lazer & criatividade")) }),
    kcard({ ico: "mood", color: acol("Amizades & social"), l: "Satisfação no lazer", v: R.lazSat == null ? "–" : `${num(R.lazSat)}<small>/5</small>`, sp: spark(H.map(h => h.lazSat), acol("Amizades & social"), { min: 1, max: 5 }) }),
  ];
  const hrs = {}; S.estudo.filter(e => mkey(e.data) >= K[0]).forEach(e => hrs[e.item] = (hrs[e.item] || 0) + (+e.horas || 0));
  const items = Object.entries(hrs).sort((a, b) => b[1] - a[1]).map(x => x[0]), top = items.slice(0, 5), pal = ["var(--a-apr)", "var(--a-car)", "var(--a-men)", "var(--a-laz)", "var(--a-fam)", "var(--muted)"];
  const ser = [...top.map((it, i) => ({ name: it, color: pal[i], data: K.map(k => sum(S.estudo.filter(e => e.item === it && mkey(e.data) === k).map(e => e.horas))) })), ...(items.length > 5 ? [{ name: "Outros", color: pal[5], data: K.map(k => sum(S.estudo.filter(e => !top.includes(e.item) && mkey(e.data) === k).map(e => e.horas))) }] : [])];
  const stages = ["Aplicado", "Entrevista", "Teste / case", "Proposta", "Aceito"], order = ["Interesse", ...stages], reach = s => S.cand.filter(c => order.indexOf(c.etapa) >= order.indexOf(s) || (["Recusado", "Desisti"].includes(c.etapa) && s === "Aplicado")).length;
  const fun = funnel([{ l: "Candidaturas", v: S.cand.length, color: acol("Carreira") }, ...stages.map((s, i) => ({ l: s, v: reach(s), color: `color-mix(in srgb, ${acol("Carreira")} ${90 - i * 14}%, var(--surface))` }))]);
  const prog = S.aprend.filter(a => a.status === "Em andamento").map(a => ({ l: a.titulo, v: +a.total ? clamp(+a.atual / +a.total) : 0, sub: `${a.tipo} · ${num(sum(S.estudo.filter(e => e.item === a.titulo).map(e => e.horas)))} h`, color: acol(a.area || "Aprendizado"), txt: pct(+a.total ? clamp(+a.atual / +a.total) : 0) }));
  const lzc = {}; S.lazer.filter(l => l.data >= addDays(TODAY, -PER * 30)).forEach(l => { const o = lzc[l.cat] ||= { h: 0, s: [], c: 0, n: 0 }; o.h += +l.horas || 0; if (isNum(l.sat)) o.s.push(+l.sat); o.c += +l.custo || 0; o.n++; });
  const lpts = Object.entries(lzc).map(([c, o], i) => ({ x: o.h, y: avg(o.s) ?? 3, r: 5 + Math.sqrt(o.c) * .9, color: pal[i % 5], label: c, tip: `${c}\n${num(o.h)} h em ${o.n} atividades\nsatisfação ${num(avg(o.s))}\ncusto ${eur(o.c)}` }));
  const books = S.aprend.filter(a => a.tipo === "Livro" && a.status === "Concluído" && a.fim).sort((a, b) => b.fim.localeCompare(a.fim));
  const body = `${vis("cr-st", "Horas de estudo por assunto", colChart(L, ser, { stacked: true, w: vw(8), h: 260, keys: K, click: "ref", sel: R.mk, fmt: v => num(v, 0) + " h", target: C.metaEstudo, targetLabel: "meta mensal" }), { cls: "s8", sub: `${PER} meses`, table: () => ({ cols: [{ l: "Mês" }, ...ser.map(s => ({ l: s.name, num: true, f: v => num(v) }))], rows: K.map((k, i) => [mlabel(k), ...ser.map(s => s.data[i])]) }) })}
    ${vis("cr-fn", "Funil de candidaturas", fun, { cls: "s4", sub: "quantas chegaram a cada etapa" })}
    ${vis("cr-cp", "Competências: atual → alvo", dumbbell(S.comp.map(c => ({ l: c.nome, a: +c.atual || 0, b: +c.alvo || 0, edit: ["comp", c.id] })), { max: 5 }), { cls: "s6", sub: "1 iniciante · 5 referência · toque para editar" })}
    ${vis("cr-pr", "O que estou aprendendo", hbars(prog, { max: 1, fmt: pct, empty: "Nada em andamento." }), { cls: "s6", sub: "progresso e horas acumuladas" })}
    ${vis("cr-lz", "Lazer: horas × satisfação", scatter(lpts, { w: vw(6), h: 270, xl: "Horas no período", yl: "Satisfação", yr: [1, 5], op: .8 }), { cls: "s6", sub: `por categoria · tamanho = custo · ${PER * 30} dias` })}
    ${vis("cr-bk", "Livros concluídos", books.length ? `<div class="list">${books.slice(0, 10).map(b => `<button type="button" class="li click" data-ent="apr|${b.id}"><div class="t">${esc(b.titulo)}<div class="m">${fmtDY(b.fim)}</div></div><span class="stars" aria-label="Nota ${b.nota || 0} de 5">${"★".repeat(+b.nota || 0)}<s>${"★".repeat(5 - (+b.nota || 0))}</s></span></button>`).join("")}</div>` : emptyChart("Nenhum livro concluído ainda."), { cls: "s6", sub: `${R.livros} no ano · meta ${C.metaLivros}` })}`;
  return reportPage(R, H, kp, body, ["Carreira", "Aprendizado", "Lazer & criatividade"]);
}

/* ---------------------------------------------------------------- Metas & tempo */
function rMetas(R) {
  const H = history(PER), f = xf(), ms = R.metas.filter(m => !f.area || m.area === f.area);
  const yI = TODAY.slice(0, 4) + "-01-01";
  const kp = [
    kcard({ ico: "target", color: acol("Carreira"), l: "Em andamento", v: R.metasAnd, sub: `${R.metas.filter(m => m.rt === "Concluída").length} concluídas` }),
    kcard({ ico: "check", color: "var(--good)", l: "No ritmo", v: R.metasRitmo, sub: "progresso ≥ tempo − 10 pts" }),
    kcard({ ico: "info", color: "var(--crit)", l: "Atrasadas ou vencidas", v: R.metasAtras, sub: R.metasAtras ? "replaneje ou quebre em tarefas" : "nenhuma" }),
    kcard({ ico: "compass", color: "var(--accent)", l: "Progresso médio", v: pct(R.metasProg), sub: "metas em andamento" }),
    kcard({ ico: "checksq", color: acol("Casa & organização"), l: "Tarefas abertas", v: R.tarAbertas, sub: R.tarAtras ? `<span class="st-crit">${R.tarAtras} atrasada(s)</span>` : "nada atrasado" }),
    kcard({ ico: "flag", color: acol("Finanças"), l: "Concluídas no ano", v: S.tarefas.filter(t => t.status === "Concluída" && t.concluida >= yI).length, sub: "tarefas" }),
  ];
  const gr = ms.filter(m => m.inicio && m.prazo).sort((a, b) => a.prazo.localeCompare(b.prazo)).map(m => ({ id: m.id, l: m.meta, ini: m.inicio, fim: m.prazo, prog: m.prog, esp: m.esp, st: m.st, rt: m.rt, color: acol(m.area) }));
  const qp = ms.filter(m => m.ativa && m.esp != null).map(m => ({ x: m.esp * 100, y: m.prog * 100, r: 7, color: acol(m.area), label: m.meta, edit: ["metas", m.id], tip: `${m.meta}\ntempo ${pct(m.esp)} · progresso ${pct(m.prog)}\n${m.rt}` }));
  const wk = []; for (let i = 11; i >= 0; i--) { const s = addDays(weekStart(TODAY), -7 * i); wk.push([fmtD(s), S.tarefas.filter(t => t.status === "Concluída" && t.concluida >= s && t.concluida < addDays(s, 7) && (!f.area || t.area === f.area)).length]); }
  const quads = ["1 · Fazer já", "2 · Agendar", "3 · Resolver rápido", "4 · Depois"], qd = ["urgente e importante", "importante", "urgente", "nem um nem outro"];
  const eis = `<div class="eis">${quads.map((q, i) => { const ts = R.tar.filter(t => t.quad === q && (!f.area || t.area === f.area)); return `<div class="eq q${i + 1}"><div class="eqh"><b>${q.slice(4)}</b><small>${qd[i]} · ${ts.length}</small></div>${ts.slice(0, 5).map(t => `<button type="button" class="eqi" data-ent="tar|${t.id}">${esc(trunc(t.tarefa, 44))}<small class="st-${t.st}">${t.prazo ? fmtD(t.prazo) : "sem prazo"}</small></button>`).join("") || `<div class="muted small">vazio</div>`}</div>`; }).join("")}</div>`;
  const byA = AREAS.map(a => { const x = R.metas.filter(m => m.area === a && m.ativa); return { a, ok: x.filter(m => ["No ritmo", "Concluída", "Sem prazo"].includes(m.rt)).length, warn: x.filter(m => m.st === "warn").length, crit: x.filter(m => m.st === "crit").length }; }).filter(x => x.ok + x.warn + x.crit);
  const projs = [...new Set(S.tarefas.map(t => t.projeto).filter(Boolean))].map(p => { const ts = R.tar.filter(t => t.projeto === p && t.status !== "Cancelada"); return { p, n: ts.length, d: ts.filter(t => t.status === "Concluída").length, a: ts.filter(t => t.st === "crit").length }; });
  const body = `${vis("mt-g", "Linha do tempo das metas", gantt(gr, { w: Math.max(vw(12), 760), lw: Math.min(260, vw(12) * .28), from: addDays(TODAY, -400), to: addDays(TODAY, 900) }), { cls: "s12", sub: "barra clara = início → prazo · preenchido = progresso · losango = onde deveria estar hoje · toque para editar" })}
    ${vis("mt-q", "Progresso × tempo decorrido", scatter(qp, { w: vw(6), h: 300, xl: "Tempo decorrido (%)", yl: "Progresso (%)", xr: [0, 100], yr: [0, 100], diag: true, fmtX: v => num(v, 0), fmtY: v => num(v, 0) }), { cls: "s6", sub: "acima da diagonal = adiantada · abaixo = atrasada" })}
    ${vis("mt-e", "Matriz de Eisenhower", eis, { cls: "s6", sub: "tarefas abertas · urgente = prazo em até 3 dias" })}
    ${vis("mt-w", "Tarefas concluídas por semana", colChart(wk.map(x => x[0]), [{ name: "Concluídas", color: "var(--good)", data: wk.map(x => x[1]) }], { w: vw(6), h: 220, legend: false, fmt: v => num(v, 0) }), { cls: "s6", sub: "12 semanas" })}
    ${vis("mt-a", "Metas por área", `<div class="stk">${byA.map(x => { const t = x.ok + x.warn + x.crit; return `<div class="stkr click" data-xf="area|${esc(x.a)}" role="button" tabindex="0"><span class="hbl">${areaDot(x.a)}${esc(ashort(x.a))}</span><div class="stkb"><i class="good" style="width:${x.ok / t * 100}%"></i><i class="warn" style="width:${x.warn / t * 100}%"></i><i class="crit" style="width:${x.crit / t * 100}%"></i></div><em>${t}</em></div>`; }).join("")}</div>${legend([{ name: "No ritmo", color: "var(--good)" }, { name: "Atenção", color: "var(--warn)" }, { name: "Em risco", color: "var(--crit)" }])}`, { cls: "s6", sub: "metas ativas · toque para filtrar" })}
    ${vis("mt-p", "Projetos", projs.length ? `<div class="list">${projs.map(p => `<button type="button" class="li click" data-ent="proj|${esc(p.p)}"><div class="t">${esc(p.p)}<div class="m">${p.d} de ${p.n} concluídas${p.a ? ` · <span class="st-crit">${p.a} atrasada(s)</span>` : ""}</div><div class="mbar"><i style="width:${p.n ? p.d / p.n * 100 : 0}%"></i></div></div></button>`).join("")}</div>` : emptyChart("Use o campo Projeto nas tarefas."), { cls: "s12" })}`;
  return reportPage(R, H, kp, body, ["Carreira", "Casa & organização"]);
}

/* ---------------------------------------------------------------- Cruzamentos (explorador) */
const CZ = { x: "sono", y: "bem", lag: 0, days: 180, gran: "d", target: "bem", rows: "m", cols: ["bem", "sono", "hab", "gasto", "estudo"] };
function metricSelect(id, val) { const ms = metricList(), gs = [...new Set(ms.map(m => m.grp))]; return `<select id="${id}" aria-label="Métrica">${gs.map(g => `<optgroup label="${esc(g)}">${ms.filter(m => m.grp === g).map(m => `<option value="${esc(m.k)}"${m.k === val ? " selected" : ""}>${esc(m.l)}</option>`).join("")}</optgroup>`).join("")}</select>`; }
function rCruz(R) {
  const H = history(PER), ms = metricList();
  if (!metric(CZ.x)) CZ.x = ms[0]?.k; if (!metric(CZ.y)) CZ.y = ms[1]?.k;
  const mx = metric(CZ.x), my = metric(CZ.y);
  if (!mx || !my) return `<div class="emptyb">${ic("scatter")}<b>Ainda não há dados para cruzar.</b><span>Faça check-ins, marque hábitos, registre gastos e escreva no diário por algumas semanas.</span></div>`;
  const c = crossData(CZ.x, CZ.y, { lag: CZ.lag, days: CZ.days, gran: CZ.gran }), jit = m => m.bin ? .15 : m.hi === 5 ? .35 : 0;
  const ctrl = `<div class="czc"><label>X ${metricSelect("czx", CZ.x)}</label><button type="button" class="iconbtn" data-act="czswap" title="Inverter X e Y" aria-label="Inverter X e Y">${ic("repeat")}</button><label>Y ${metricSelect("czy", CZ.y)}</label>
    <label>Defasagem <select id="czlag">${[[0, "mesmo período"], [1, "Y no período seguinte"], [2, "2 períodos depois"], [7, "7 períodos depois"]].map(([v, l]) => `<option value="${v}"${CZ.lag === v ? " selected" : ""}>${l}</option>`).join("")}</select></label>
    <label>Janela <select id="czdays">${[[90, "90 dias"], [180, "6 meses"], [365, "1 ano"], [730, "2 anos"]].map(([v, l]) => `<option value="${v}"${CZ.days === v ? " selected" : ""}>${l}</option>`).join("")}</select></label>
    <div class="segs">${[["d", "Dia"], ["w", "Semana"], ["m", "Mês"]].map(([k, l]) => `<button type="button" class="seg" data-czgran="${k}" aria-pressed="${CZ.gran === k}">${l}</button>`).join("")}</div></div>`;
  const read = !c || c.n < 5 ? `<div class="empty">Poucos pontos em comum (${c?.n || 0}). Aumente a janela ou escolha outras métricas.</div>` : `<div class="czr"><div class="czbig"><b>${c.r == null ? "–" : num(c.r, 2)}</b><span>correlação ${c.r == null ? "" : rWord(c.r)}${c.r != null && Math.abs(c.r) >= .15 ? (c.r > 0 ? " positiva" : " negativa") : ""}</span><small>${plural(c.n, CZ.gran === "d" ? "dia" : CZ.gran === "w" ? "semana" : "mês", CZ.gran === "d" ? "dias" : CZ.gran === "w" ? "semanas" : "meses")} com os dois registros</small></div>
    ${c.groups ? `<div class="czg"><div><span>${c.groups.bin ? "Com" : "X alto"}</span><b>${mfmt(CZ.y, c.groups.a)}</b><div class="mbar"><i style="width:${clamp(c.groups.a / Math.max(c.groups.a, c.groups.b, 1e-9)) * 100}%"></i></div></div><div><span>${c.groups.bin ? "Sem" : "X baixo"}</span><b>${mfmt(CZ.y, c.groups.b)}</b><div class="mbar"><i style="width:${clamp(c.groups.b / Math.max(c.groups.a, c.groups.b, 1e-9)) * 100}%"></i></div></div></div>` : ""}
    <p>${c.groups ? `${c.groups.bin ? `Nos ${CZ.gran === "d" ? "dias" : "períodos"} com <b>${esc(mx.l.toLowerCase())}</b>` : `No terço com <b>${esc(mx.l.toLowerCase())}</b> mais alto`}, <b>${esc(my.l.toLowerCase())}</b> fica em ${mfmt(CZ.y, c.groups.a)}, contra ${mfmt(CZ.y, c.groups.b)} ${c.groups.bin ? "sem" : "no terço mais baixo"}${CZ.lag ? ` (${CZ.lag} período(s) depois)` : ""}.` : ""}${c.fit && !mx.bin ? ` Cada unidade a mais em X acompanha ${sgn(c.fit.b, v => num(v, 3))} em Y.` : ""}</p>
    <p class="note">Correlação mostra que as coisas andam juntas, não que uma causa a outra. Use como hipótese para testar.</p>
    <div class="row wrap"><button type="button" class="btn sm" data-czask="1">${ic("spark")}Pedir leitura ao Conselho</button></div></div>`;
  const D = DAILY(), s0 = Math.max(0, D.N - CZ.days);
  const ts = CZ.gran === "d" ? { labels: D.dates.slice(s0).map(fmtD), a: movAvg(D.C[CZ.x].slice(s0), 7), b: movAvg(D.C[CZ.y].slice(s0), 7) } : (() => { const n = CZ.gran === "w" ? Math.ceil(CZ.days / 7) : Math.max(3, Math.ceil(CZ.days / 30)), A = aggSeries(CZ.x, CZ.gran, n), B = aggSeries(CZ.y, CZ.gran, n); return { labels: A.labels, a: A.vals, b: B.vals }; })();
  const bv = ts.b.filter(isNum), rlo = Math.min(...bv), rhi = Math.max(...bv), rsc = niceScale(isFinite(rlo) ? rlo : 0, isFinite(rhi) ? rhi : 1, 4);
  const tl = lineChart(ts.labels, [{ name: mx.l, color: "var(--accent)", data: ts.a, fmt: v => mx.fmt(v) }, { name: my.l, color: "var(--a-fis)", data: ts.b, right: true, fill: false }], { w: vw(12), h: 250, zero: false, right: { min: rsc.lo, max: rsc.hi, fmt: v => my.fmt(v) }, fmt: v => mx.fmt(v), maxLabels: 12, dots: false });
  const core = CORE_KEYS.filter(k => metric(k));
  const inf = influencers(CZ.target, { days: CZ.days, min: 20 }).slice(0, 10);
  const pv = pivot();
  const body = `<div class="s12">${ctrl}</div>
    ${vis("cz-sc", `${esc(mx.l)} × ${esc(my.l)}`, scatter(c?.pts || [], { w: vw(7), h: 320, xl: mx.l, yl: my.l, jitter: [jit(mx), jit(my)], fit: true, fmtX: v => mx.fmt(v), fmtY: v => my.fmt(v), op: CZ.gran === "d" ? .4 : .75 }), { cls: "s7", sub: `cada ponto = ${CZ.gran === "d" ? "um dia" : CZ.gran === "w" ? "uma semana" : "um mês"}${CZ.lag ? ` · Y deslocado ${CZ.lag}` : ""}`, table: () => ({ cols: [{ l: "Período" }, { l: mx.l, num: true }, { l: my.l, num: true }], rows: (c?.pts || []).map(p => [p.d, p.x, p.y]) }) })}
    ${vis("cz-rd", "Leitura", read, { cls: "s5", nofocus: true })}
    ${vis("cz-tl", "Lado a lado no tempo", tl, { cls: "s12", sub: CZ.gran === "d" ? "média móvel de 7 dias · Y no eixo da direita" : "Y no eixo da direita" })}
    ${vis("cz-mx", "Matriz de correlação", corrHeat(core, { days: CZ.days }), { cls: "s7", sub: `${CZ.days} dias · azul = andam juntos · vermelho = em sentidos opostos · toque numa célula para cruzar` })}
    ${vis("cz-in", "O que mais acompanha…", `<div class="row wrap"><label class="inl">Alvo ${metricSelect("cztg", CZ.target)}</label></div>${diverge(inf.map(i => ({ l: i.l, v: i.r, sub: i.groups ? `${i.groups.bin ? "com" : "alto"} ${mfmt(CZ.target, i.groups.a)} × ${i.groups.bin ? "sem" : "baixo"} ${mfmt(CZ.target, i.groups.b)} · ${i.n} dias` : `${i.n} dias`, go: `data-cx="${i.k}|${CZ.target}"` })), { fmt: v => "r " + num(v, 2), max: 1, empty: "Poucos dados." })}`, { cls: "s5", sub: "as métricas mais correlacionadas com o alvo · toque para cruzar" })}
    ${vis("cz-pv", "Tabela dinâmica", pv.html, { cls: "s12", sub: "linhas por período · colunas são métricas · cor = intensidade na coluna", table: () => pv.table })}`;
  return `${xfBar()}<div class="rep"><div class="repmain"><div class="vg">${body}</div></div>${rail(R, H, null)}</div>`;
}
function pivot() {
  const cols = CZ.cols.filter(k => metric(k)), dimL = { m: "Mês", w: "Semana", dow: "Dia da semana" }[CZ.rows];
  let rows = [];
  if (CZ.rows === "dow") { const D = DAILY(), s0 = Math.max(0, D.N - CZ.days); rows = [1, 2, 3, 4, 5, 6, 0].map(w => [DOWL[w], ...cols.map(k => avg(D.C[k].slice(s0).filter((v, i) => parse(D.dates[s0 + i]).getDay() === w)))]); }
  else { const n = CZ.rows === "w" ? 12 : 12, ss = cols.map(k => aggSeries(k, CZ.rows, n)), keys = ss[0]?.keys || []; rows = keys.map((k, i) => [CZ.rows === "w" ? "sem. " + fmtD(k) : mlabel(k), ...ss.map(s => s.vals[i])]).reverse(); }
  const rng = cols.map((k, j) => { const v = rows.map(r => r[j + 1]).filter(isNum); return [Math.min(...v), Math.max(...v)]; });
  const add = metricList().filter(m => !cols.includes(m.k));
  const html = `<div class="pvc"><span class="flbl">Linhas</span><div class="segs">${[["m", "Mês"], ["w", "Semana"], ["dow", "Dia da semana"]].map(([k, l]) => `<button type="button" class="seg" data-pvrows="${k}" aria-pressed="${CZ.rows === k}">${l}</button>`).join("")}</div><span class="flbl">Colunas</span>${cols.map(k => `<span class="chip">${esc(metric(k).l)}<button type="button" class="chipx" data-pvdel="${k}" aria-label="Remover ${esc(metric(k).l)}">${ic("x")}</button></span>`).join("")}${cols.length < 8 ? `<select id="pvadd" aria-label="Adicionar coluna"><option value="">+ métrica</option>${add.map(m => `<option value="${esc(m.k)}">${esc(m.l)}</option>`).join("")}</select>` : ""}</div>
    <div class="hscroll"><table class="dt pv"><thead><tr><th>${dimL}</th>${cols.map(k => `<th class="num">${esc(metric(k).l)}<small>${metric(k).agg === "sum" ? "soma" : "média"}</small></th>`).join("")}</tr></thead><tbody>${rows.map(r => `<tr><td>${esc(r[0])}</td>${cols.map((k, j) => { const v = r[j + 1], [lo, hi] = rng[j], t = isNum(v) && hi > lo ? (v - lo) / (hi - lo) : .5, inv = metric(k).inv; return `<td class="num" style="background:${isNum(v) ? `color-mix(in srgb, ${inv ? "var(--crit)" : "var(--accent)"} ${Math.round((inv ? t : t) * 38)}%, transparent)` : "transparent"}">${isNum(v) ? esc(metric(k).fmt(v)) : "–"}</td>`; }).join("")}</tr>`).join("")}</tbody></table></div>`;
  return { html, table: { cols: [{ l: dimL }, ...cols.map(k => ({ l: metric(k).l, num: true, f: v => v == null ? "" : metric(k).fmt(v) }))], rows } };
}
function reportClick(t) {
  const ds = t.dataset;
  if (ds.hscal) { HSV.cal = ds.hscal; render(); return true; }
  if (ds.cx) { const [a, b] = ds.cx.split("|"); CZ.x = a; CZ.y = b; DRAWER = null; if (PAGE !== "cruz") setHash("cruz"); else { render(); window.scrollTo({ top: 0, behavior: "smooth" }); } return true; }
  if (ds.act === "czswap") { [CZ.x, CZ.y] = [CZ.y, CZ.x]; render(); return true; }
  if (ds.czgran) { CZ.gran = ds.czgran; render(); return true; }
  if (ds.pvrows) { CZ.rows = ds.pvrows; render(); return true; }
  if (ds.pvdel) { CZ.cols = CZ.cols.filter(k => k !== ds.pvdel); render(); return true; }
  if (ds.czask) { const mx = metric(CZ.x), my = metric(CZ.y), c = crossData(CZ.x, CZ.y, { lag: CZ.lag, days: CZ.days, gran: CZ.gran }); MST.input.conselho = `Cruzei ${mx.l} × ${my.l} nos últimos ${CZ.days} dias (${CZ.gran === "d" ? "por dia" : CZ.gran === "w" ? "por semana" : "por mês"}${CZ.lag ? `, Y ${CZ.lag} período(s) depois` : ""}): r = ${c?.r == null ? "?" : num(c.r, 2)} em ${c?.n || 0} pontos${c?.groups ? `; Y com X alto/sim ${mfmt(CZ.y, c.groups.a)} × baixo/não ${mfmt(CZ.y, c.groups.b)}` : ""}. Como você interpreta isso no meu caso e que experimento de 2 semanas eu poderia fazer para testar?`; setHash("mentor", "conselho"); return true; }
  if (ds.mquick) { const v = ($("#mq_" + ds.mquick)?.value || "").trim(); if (!v) { setHash("mentor", ds.mquick); return true; } setHash("mentor", ds.mquick); setTimeout(() => askMentor(ds.mquick, v), 80); return true; }
  return false;
}
function reportChange(t) {
  const v = t.value;
  if (t.id === "czx") { CZ.x = v; render(); return true; } if (t.id === "czy") { CZ.y = v; render(); return true; }
  if (t.id === "czlag") { CZ.lag = +v; render(); return true; } if (t.id === "czdays") { CZ.days = +v; render(); return true; }
  if (t.id === "cztg") { CZ.target = v; render(); return true; }
  if (t.id === "pvadd" && v) { CZ.cols.push(v); render(); return true; }
  return false;
}
