
/* ================================================================ páginas de registro (onde os dados entram) */
let CHECKIN = null;
const TF = { q: "", status: "abertas", area: "", proj: "" }, LF = { q: "", tipo: "", cat: "" };
function quickBox(id, ph, act, hint) { return `<div class="quick"><span class="qi">${ic("bolt")}</span><input id="${id}" type="text" placeholder="${esc(ph)}" aria-label="${esc(ph)}" autocomplete="off"><button type="button" class="btn sm primary" data-act="${act}">Adicionar</button></div><div class="qhint" id="${id}_h">${hint}</div>`; }

/* ---------------------------------------------------------------- Hoje */
function pHoje(R) {
  const e = S.saude[TODAY] || {}, H = history(3);
  const scale = (k, lbl) => `<div class="sc1"><span class="flbl">${lbl}</span><div class="mchips">${[1, 2, 3, 4, 5].map(v => `<button type="button" class="mchip m${k === "estresse" ? 6 - v : v}" data-sd="${k}" data-v="${v}" data-day="${TODAY}" aria-pressed="${e[k] == v}">${v}</button>`).join("")}</div></div>`;
  const habs = R.hab.map(h => { const on = !!S.marks[`${h.id}|${TODAY}`]; return `<button type="button" class="hbtn${on ? " on" : ""}" data-mark="${h.id}|${TODAY}" aria-pressed="${on}" style="--c:${acol(h.area)}"><span class="hck">${ic("check")}</span><span class="hn">${esc(h.nome)}<small>${h.streak ? `${plural(h.streak, "dia", "dias")} seguidos` : ashort(h.area)}</small></span></button>`; }).join("");
  const tasks = R.tar.filter(t => t.open && t.prazo && t.prazo <= TODAY).sort((a, b) => a.prazo.localeCompare(b.prazo));
  const doneToday = R.tar.filter(t => t.status === "Concluída" && t.concluida === TODAY);
  const ents = S.diario.filter(x => x.data === TODAY);
  const urgent = R.areas.filter(a => a.dados != null && aativa(a.a)).sort((a, b) => a.dados - b.dados)[0], umid = urgent ? AREA_INFO[urgent.a].id : "conselho";
  const ins = insights(R, H)[0], exps = (S.experimentos || []).filter(x => x.status === "ativo" && expSchedule(x)[TODAY] && !(x.desenho === "antes" && expSchedule(x)[TODAY] === "A")), al = radarAlerts().slice(0, 2);
  const fwk = fsTarget(), fpend = parse(TODAY).getDay() <= 1 && S.fechamentos?.[fwk]?.status !== "fechado";
  return `<div class="g2c hj">
      ${panel(`${ic("bolt")}Capturar <small>escreva ou dite o dia; o Atlas separa os registros</small>`, captureFormHTML("h"), { cls: "span2 capcard", act: `<a class="lnk" href="#painel">${ic("mic")}Painel do dia</a>` })}
      ${fpend ? `<div class="pn fscta span2"><div>${ic("week")}<b>Hora de fechar a semana de ${wkLabel(fwk)}</b><small>Números, destaques do diário, o que você cumpriu e as prioridades da próxima. Uns 15 minutos.</small></div><a class="btn primary" href="#semana">Fechar a semana</a></div>` : ""}
      ${bmHoje()}
      ${jHoje()}
      ${exps.length ? panel(`${ic("flask")}Experimento de hoje`, exps.map(x => `<div class="hjexp"><b>${esc(x.titulo)}</b>${expToday(x, expAnalyze(x))}</div>`).join(""), { act: `<a class="lnk" href="#exp">ver análise</a>` }) : ""}
      ${al.length ? panel(`${ic("radar")}No radar`, al.map(a => alertCard(a, true)).join(""), { act: `<a class="lnk" href="#radar">ver tudo</a>` }) : ""}
      ${panel(`${ic("pulse")}Check-in de hoje <small>salva sozinho</small>`, `<div class="ck3">${scale("humor", "Humor")}${scale("energia", "Energia")}${scale("estresse", "Estresse")}</div>
        <div class="form f4"><label>Sono (h)<input id="hj_sono" type="number" step="0.5" data-sdi="sono" data-day="${TODAY}" value="${e.sono ?? ""}"></label><label>Treino<select id="hj_treino" data-sdi="treino" data-day="${TODAY}"><option></option>${TREINOS.map(t => `<option${e.treino === t ? " selected" : ""}>${esc(t)}</option>`).join("")}</select></label><label>Minutos<input id="hj_min" type="number" data-sdi="min" data-day="${TODAY}" value="${e.min ?? ""}"></label><label>Passos<input id="hj_passos" type="number" data-sdi="passos" data-day="${TODAY}" value="${e.passos ?? ""}"></label></div>`)}
      ${mentorMini(umid)}
      ${panel(`${ic("repeat")}Hábitos de hoje <small>${R.hab.filter(h => S.marks[`${h.id}|${TODAY}`]).length} de ${R.hab.length}</small>`, habs ? `<div class="hgrid2">${habs}</div>` : `<div class="empty">Crie hábitos em Hábitos › Marcar hábitos.</div>`, { act: `<a class="lnk" href="#hab.marcar">ver semana</a>` })}
      ${ins ? `<div class="pn"><div class="insight ${ins.st}"><div class="ik">${esc(ins.k)}</div><p>${ins.t}</p><p class="ia">${esc(ins.a)}</p></div></div>` : ""}
      <div class="span2 hjd"><div class="dhead">${composerHTML()}</div>
      ${ents.length ? `<div class="mhead">Hoje no diário<small>${plural(ents.length, "entrada", "entradas")}</small></div>${ents.map(x => entryCard(x)).join("")}` : ""}
      </div>
      ${panel(`${ic("flag")}Prioridades da semana`, `<div class="prio">${[0, 1, 2].map(i => `<label><span>${i + 1}</span><input id="prio${i}" type="text" data-prio="${i}" value="${esc(S.prio[i] || "")}" placeholder="O que mais importa"></label>`).join("")}</div>`)}
      ${panel(`${ic("checksq")}Para hoje <small>${tasks.length ? tasks.length + " pendente(s)" : "em dia"}</small>`, `${tasks.map(t => `<div class="li"><label class="ckl"><input type="checkbox" data-tdone="${t.id}"><span>${esc(t.tarefa)}<small class="st-${t.st}">${t.prazo < TODAY ? `atrasada ${relDay(t.prazo)}` : "vence hoje"}</small></span></label></div>`).join("")}${doneToday.map(t => `<div class="li"><label class="ckl"><input type="checkbox" data-tdone="${t.id}" checked><span class="done">${esc(t.tarefa)}</span></label></div>`).join("")}${!tasks.length && !doneToday.length ? `<div class="empty">Nada vencendo hoje.</div>` : ""}${quickBox("hj_tar", "Nova tarefa: Ligar para o banco até sexta !alta", "qtar", "Prazo (até 15/10, amanhã, sexta), prioridade (!alta) e #área são opcionais.")}`)}
      ${panel(`${ic("cal")}Próximos 7 dias`, agenda(R, 7))}
    </div>`;
}

/* ---------------------------------------------------------------- Roda da Vida e revisão */
function pRoda(R) {
  const mk = R.mk, cur = S.roda[mk] || {}, rv = S.revisao[mk] || {};
  return `<div class="g2c">
    ${panel(`Notas de ${mlabel(mk)} <small>0 = péssimo · 10 = pleno</small>`, AREAS.map((a, i) => `<div class="range"><label for="r${i}">${areaDot(a)}${esc(ashort(a))}</label><input id="r${i}" type="range" min="0" max="10" step="1" value="${cur[a] ?? 5}" data-roda="${esc(a)}" style="accent-color:${acol(a)}"><output>${cur[a] ?? "–"}</output><span class="muted small">dados ${R.areas[i].dados == null ? "–" : num(R.areas[i].dados)}</span></div>`).join("") + `<p class="note">Mover o controle grava a nota do mês escolhido no topo. A coluna “dados” mostra o placar calculado dos seus registros, para comparar com a sensação.</p>`)}
    ${panel("Percepção × dados × alvo", radar(R.areas) + `<div class="flbl">Alvos por área</div><div class="form f3">${AREAS.map((a, i) => `<label>${esc(ashort(a))}<input id="alvo${i}" type="number" min="0" max="10" data-alvo="${esc(a)}" value="${S.alvo[a] ?? ""}"></label>`).join("")}</div>`)}
    ${panel(`Revisão mensal · ${mlabel(mk)} <small>15 minutos no último dia do mês</small>`, `<div class="form f2">${[["vitorias", "Vitórias e destaques"], ["naofunc", "O que não funcionou"], ["aprendi", "O que aprendi"], ["foco", "Foco do próximo mês"]].map(([k, l]) => `<label>${l}<textarea id="rev_${k}" data-rev="${k}">${esc(rv[k] || "")}</textarea></label>`).join("")}<label>Nota do mês (0–10)<input id="rev_nota" type="number" min="0" max="10" data-rev="nota" value="${rv.nota ?? ""}"></label></div><div class="row wrap"><button type="button" class="btn sm" data-act="revnotion">${ic("upload")}Enviar revisão ao Notion</button><a class="btn sm ghost" href="#mentor.conselho">${ic("spark")}Revisar com o Conselho</a></div>`, { cls: "span2" })}
    ${panel("Histórico da Roda", `<div class="hscroll"><table class="dt"><thead><tr><th>Área</th>${R.series.map(s => `<th class="num">${mabbr(s.mk)}</th>`).join("")}</tr></thead><tbody>${AREAS.map(a => `<tr><td>${areaDot(a)}${esc(ashort(a))}</td>${R.series.map(s => { const v = S.roda[s.mk]?.[a]; return `<td class="num" style="${v != null ? `background:color-mix(in srgb, ${v >= 5 ? "var(--good)" : "var(--crit)"} ${Math.abs(v - 5) * 8}%, transparent)` : ""}">${v ?? ""}</td>`; }).join("")}</tr>`).join("")}</tbody></table></div>`, { cls: "span2" })}</div>`;
}

/* ---------------------------------------------------------------- Metas e tarefas */
function pMetasLista(R) {
  const ord = [...R.metas].sort((a, b) => (a.rt === "Concluída") - (b.rt === "Concluída") || (a.prazo || "9").localeCompare(b.prazo || "9"));
  const hz = h => R.metas.filter(m => m.hz === h && m.ativa && m.rt !== "Concluída").length;
  return `${kpiRow([kmini("var(--accent)", "Em andamento", R.metasAnd, `concluídas: ${R.metas.filter(m => m.rt === "Concluída").length}`), kmini("var(--good)", "No ritmo", R.metasRitmo, "progresso ≥ tempo − 10 pts", "good"), kmini("var(--crit)", "Atrasadas ou vencidas", R.metasAtras, R.metasAtras ? "replaneje ou ajuste o prazo" : "nenhuma", R.metasAtras ? "crit" : "good"), kmini("var(--a-apr)", "Por horizonte", `${hz("Curto")} · ${hz("Médio")} · ${hz("Longo")}`, "curto ≤ 6 meses · médio ≤ 2 anos")])}
    ${panel("Metas", table("metas", ord, [["Meta", m => `<b>${esc(m.meta)}</b><div class="muted small">${esc(m.proximo || "")}</div>`], ["Área", m => areaTag(m.area)], ["Horizonte", m => m.hz, "opt"], ["Progresso", m => `<div class="pbar"><span>${pct(m.prog)}</span><div class="bt"><i class="${m.st}" style="width:${m.prog * 100}%"></i>${m.esp != null ? `<b style="left:${m.esp * 100}%"></b>` : ""}</div></div>`], ["Ritmo", m => pill(m.st, m.rt)], ["Dias", m => m.dias ?? "", "num opt"], ["Tarefas", m => m.abertas || "", "num opt"]], { empty: "Escreva de 3 a 7 metas mensuráveis, cada uma ligada a uma área." }), { act: addBtn("metas", "Nova meta") })}`;
}
function pTarefas(R) {
  const projs = [...new Set(S.tarefas.map(t => t.projeto).filter(Boolean))].sort(), q = norm(TF.q);
  const list = R.tar.filter(t => (TF.status === "todas" || (TF.status === "abertas" ? t.open : TF.status === "atrasadas" ? t.st === "crit" : t.status === "Concluída")) && (!TF.area || t.area === TF.area) && (!TF.proj || t.projeto === TF.proj) && (!q || norm(t.tarefa + " " + t.projeto + " " + (t.notas || "")).includes(q)))
    .sort((a, b) => (!a.open) - (!b.open) || (a.prazo || "9").localeCompare(b.prazo || "9"));
  return `${kpiRow([kmini("var(--accent)", "Abertas", R.tarAbertas, `alta prioridade: ${R.tar.filter(t => t.open && t.prio === "Alta").length}`), kmini("var(--crit)", "Atrasadas", R.tarAtras, R.tarAtras ? "resolva ou replaneje" : "nada atrasado", R.tarAtras ? "crit" : "good"), kmini("var(--warn)", "Vencem em 7 dias", R.tar7, "inclui hoje", R.tar7 ? "warn" : ""), kmini("var(--good)", "Concluídas no mês", R.tarConcl, mlabel(R.mk))])}
    ${panel("Adicionar rápido", quickBox("qt_in", "Ex.: Mandar o portfólio para a recrutadora até 10/10 !alta #carreira", "qtar", "Escreva naturalmente: prazo (até 15/10, amanhã, sexta, em 3 dias), prioridade (!alta, !baixa) e #área são reconhecidos."))}
    ${panel(`Tarefas <small>${plural(list.length, "tarefa", "tarefas")}</small>`, `<div class="filters"><div class="dsearch">${ic("search")}<input id="tf_q" type="search" placeholder="Filtrar" value="${esc(TF.q)}" aria-label="Filtrar tarefas"></div><div class="segs">${[["abertas", "Abertas"], ["atrasadas", "Atrasadas"], ["feitas", "Feitas"], ["todas", "Todas"]].map(([k, l]) => `<button type="button" class="seg" data-tfs="${k}" aria-pressed="${TF.status === k}">${l}</button>`).join("")}</div><select id="tf_area" aria-label="Área"><option value="">Todas as áreas</option>${AREAS.map(a => `<option value="${esc(a)}"${TF.area === a ? " selected" : ""}>${esc(ashort(a))}</option>`).join("")}</select><select id="tf_proj" aria-label="Projeto"><option value="">Todos os projetos</option>${projs.map(p => `<option${TF.proj === p ? " selected" : ""}>${esc(p)}</option>`).join("")}</select></div>
      ${list.length ? `<div class="tlist">${list.map(t => `<div class="trow${t.open ? "" : " done"}"><label class="ckl"><input type="checkbox" data-tdone="${t.id}"${t.status === "Concluída" ? " checked" : ""} aria-label="Concluir ${esc(t.tarefa)}"><span></span></label><button type="button" class="tmain" data-ent="tar|${t.id}"><b>${esc(t.tarefa)}</b><small>${[t.projeto, t.meta && "meta: " + t.meta, t.origem && t.origem !== "diário" ? "via " + t.origem : t.origem === "diário" ? "via diário" : ""].filter(Boolean).map(esc).join(" · ")}</small></button>${t.area ? areaTag(t.area) : ""}<span class="tprio p-${slug(t.prio || "")}">${esc(t.prio || "")}</span><span class="tdue">${t.prazo ? fmtD(t.prazo) : ""}</span>${pill(t.st, t.al)}<button type="button" class="vb" data-edit="tarefas" data-id="${t.id}" aria-label="Editar">${ic("edit")}</button></div>`).join("")}</div>` : `<div class="empty">Nenhuma tarefa com esses filtros.</div>`}`, { act: addBtn("tarefas", "Nova tarefa") })}`;
}

/* ---------------------------------------------------------------- Finanças: lançamentos e orçamento */
function pLanc(R) {
  const F = R.fin, q = norm(LF.q), lm = R.lm.filter(l => (!LF.tipo || l.tipo === LF.tipo) && (!LF.cat || l.cat === LF.cat) && (!q || norm(l.desc + " " + l.cat).includes(q))).sort((a, b) => b.data.localeCompare(a.data));
  const cats = [...new Set(R.lm.map(l => l.cat))].sort();
  return `${kpiRow([kmini(acol("Finanças"), "Receitas", eur(F.rec), mlabel(R.mk)), kmini(GCOL["Estilo de vida"], "Despesas", eur(F.desp), R.orcTot ? `${pct(F.desp / R.orcTot)} do orçamento` : "orçamento não definido", R.orcTot ? (F.desp > R.orcTot ? "crit" : "good") : ""), kmini("var(--accent)", "Resultado", eur(F.res), `aportes ${eur(F.apo)} · caixa ${eur(F.res - F.apo)}`, F.res >= 0 ? "good" : "crit"), kmini(GCOL["Poupança"], "Taxa de poupança", pct(F.taxa), `meta ${pct(S.cfg.metaPoup)}`, F.taxa == null ? "" : F.taxa >= S.cfg.metaPoup ? "good" : "warn")])}
    ${panel("Lançar rápido", quickBox("ql_in", "Ex.: 12,50 Almoço  ·  +2450 Salário  ·  >200 Reserva de emergência", "qlanc", "Valor e descrição. A categoria é sugerida pelo seu histórico e pelas regras. Use + para receita e > para aporte. A data é hoje."))}
    ${panel(`Lançamentos de ${mlabel(R.mk)} <small>${plural(lm.length, "lançamento", "lançamentos")}</small>`, `<div class="filters"><div class="dsearch">${ic("search")}<input id="lf_q" type="search" placeholder="Filtrar" value="${esc(LF.q)}" aria-label="Filtrar lançamentos"></div><div class="segs">${[["", "Todos"], ["Despesa", "Despesas"], ["Receita", "Receitas"], ["Aporte", "Aportes"]].map(([k, l]) => `<button type="button" class="seg" data-lft="${k}" aria-pressed="${LF.tipo === k}">${l}</button>`).join("")}</div><select id="lf_cat" aria-label="Categoria"><option value="">Todas as categorias</option>${cats.map(c => `<option${LF.cat === c ? " selected" : ""}>${esc(c)}</option>`).join("")}</select><a class="lnk" href="#integ">Importar extrato (CSV)</a></div>
      ${table("lanc", lm, [["Data", l => fmtD(l.data), "num"], ["Tipo", l => `<span class="tipo t-${slug(l.tipo)}">${esc(l.tipo)}</span>`], ["Categoria", l => l.tipo === "Despesa" ? `<span class="gtag" style="--c:${GCOL[CAT_DESP[l.cat] || "Estilo de vida"]}">${esc(l.cat)}</span>` : esc(l.cat)], ["Descrição", l => esc(l.desc) + (l.origem ? ` <span class="chip xs">${esc(l.origem)}</span>` : "")], ["Conta", l => esc(l.conta || ""), "opt"], ["Valor", l => `<span class="${l.tipo === "Receita" ? "st-good" : ""}">${eur(+l.valor, 2)}</span>`, "num"]], { empty: "Nenhum lançamento neste mês." })}`, { act: addBtn("lanc", "Novo lançamento") })}`;
}
function pOrc(R) {
  const F = R.fin, p = S.patr[R.mk] || {};
  return `<div class="g2c">${panel(`Orçamento por categoria <small>uso · ritmo do mês ${pct(R.ritmo)}</small>`, `<div class="orcl">${Object.keys(CAT_DESP).map(c => { const x = R.orcCats.find(o => o.cat === c) || { real: 0, plan: 0, p: null, st: null }; return `<div class="orcr"><span>${esc(c)}<small>${esc(CAT_DESP[c])}</small></span><div class="bt"><i class="${x.st || "none"}" style="width:${clamp(x.p ?? 0) * 100}%"></i><u style="left:${R.ritmo * 100}%"></u></div><em>${eur(x.real)}</em><input id="orc_${slug(c)}" type="number" aria-label="Orçamento de ${esc(c)}" data-orc="${esc(c)}" value="${S.orc[c] ?? ""}" placeholder="plano"></div>`; }).join("")}</div><div class="orct"><span>Total planejado</span><b>${eur(R.orcTot)}</b><span>Gasto até agora</span><b>${eur(F.desp)}</b>${R.proj != null ? `<span>Projeção do mês</span><b class="${R.proj > R.orcTot ? "st-crit" : "st-good"}">${eur(R.proj)}</b>` : ""}</div>`)}
    <div class="stack">${panel(`Patrimônio · fim de ${mlabel(R.mk)} <small>preencha no fim do mês</small>`, `<div class="form f2">${[["contas", "Contas e caixa"], ["reserva", "Reserva de emergência"], ["invest", "Investimentos"], ["outros", "Outros bens"], ["dividas", "(−) Dívidas"]].map(([k, l]) => `<label>${l}<input id="patr_${k}" type="number" data-patr="${k}" value="${p[k] ?? ""}"></label>`).join("")}</div><div class="minis">${kmini("var(--accent)", "Patrimônio líquido", R.pl == null ? "–" : eur(R.pl), R.plVar == null ? "" : `${sgn(R.plVar, eur)} no mês`)}${kmini(GCOL["Poupança"], "Reserva cobre", R.reserva == null ? "–" : num(R.reserva) + " meses", `meta ${S.cfg.metaReserva}`)}</div>`)}
    ${panel("Distribuição da receita <small>referência 50/30/20</small>", hbars([...R.dist.map(d => ({ l: d.g, v: F.rec ? d.v / F.rec : 0, color: GCOL[d.g] })), { l: "Poupança", v: F.rec ? Math.max(0, F.res) / F.rec : 0, color: GCOL["Poupança"] }], { fmt: pct, max: 1 }))}
    ${panel(`Assinaturas <small>${eur(sum(R.ass.map(a => a.mensal)), 2)} por mês</small>`, table("assin", R.ass, [["Serviço", a => `<b>${esc(a.servico)}</b>`], ["Por mês", a => eur(a.mensal, 2), "num"], ["Uso", a => a.uso === "Baixo" ? pill("crit", "cancelar?") : esc(a.uso)]]), { act: addBtn("assin", "Nova") })}
    ${panel("Regras de categorização <small>usadas no lançamento rápido e na importação</small>", table("regras", S.regras, [["Se contém", r => `<b>${esc(r.termo)}</b>`], ["Tipo", r => esc(r.tipo || "Despesa")], ["Categoria", r => esc(r.cat)]], { empty: "Sem regras. Elas também são aprendidas do seu histórico." }), { act: addBtn("regras", "Nova regra") })}${finFontes()}</div></div>`;
}

/* ---------------------------------------------------------------- Saúde: check-in */
function pCheckin(R) {
  const day = CHECKIN || TODAY, e = S.saude[day] || {};
  const scale = (k, lbl, inv) => `<div class="sc1"><span class="flbl">${lbl} ${inv ? "(1 tranquilo · 5 tenso)" : "(1 ruim · 5 ótimo)"}</span><div class="mchips">${[1, 2, 3, 4, 5].map(v => `<button type="button" class="mchip m${inv ? 6 - v : v}" data-sd="${k}" data-v="${v}" data-day="${day}" aria-pressed="${e[k] == v}">${v}</button>`).join("")}</div></div>`;
  const last = Object.entries(S.saude).sort((a, b) => b[0].localeCompare(a[0])).slice(0, 21), dc = dayContext(day);
  return `${kpiRow([kmini(acol("Saúde física"), "Sono médio", R.sono == null ? "–" : num(R.sono) + " h", `meta ${num(S.cfg.metaSono)} h`, R.sono == null ? "" : R.sono >= S.cfg.metaSono ? "good" : "warn"), kmini(acol("Saúde mental"), "Humor médio", R.humor == null ? "–" : num(R.humor) + "/5", `energia ${num(R.energia)} · estresse ${num(R.estresse)}`), kmini(acol("Carreira"), "Treinos", R.treinos, `${R.minTreino} min · meta ${Math.round(S.cfg.metaTreinos * R.DR / 7)}`), kmini(acol("Finanças"), "Peso atual", R.peso == null ? "–" : num(R.peso) + " kg", `${R.diasReg} dias registrados no mês`)])}
    <div class="g2c">${panel(`Check-in de ${day === TODAY ? "hoje" : fmtDL(day)}`, `<div class="row"><input type="date" id="ck_day" value="${day}" aria-label="Dia do check-in">${day !== TODAY ? `<button type="button" class="btn sm ghost" data-ckday="${TODAY}">Voltar para hoje</button>` : ""}</div>
      <div class="ck3">${scale("humor", "Humor")}${scale("energia", "Energia")}${scale("estresse", "Estresse", 1)}${scale("qual", "Qualidade do sono")}</div>
      <div class="form f3"><label>Sono (h)<input id="sd_sono" type="number" step="0.5" data-sdi="sono" data-day="${day}" value="${e.sono ?? ""}"></label><label>Treino<select id="sd_treino" data-sdi="treino" data-day="${day}"><option></option>${TREINOS.map(t => `<option${e.treino === t ? " selected" : ""}>${esc(t)}</option>`).join("")}</select></label><label>Treino (min)<input id="sd_min" type="number" data-sdi="min" data-day="${day}" value="${e.min ?? ""}"></label><label>Passos<input id="sd_passos" type="number" data-sdi="passos" data-day="${day}" value="${e.passos ?? ""}"></label><label>Peso (kg)<input id="sd_peso" type="number" step="0.1" data-sdi="peso" data-day="${day}" value="${e.peso ?? ""}"></label></div>
      <label class="full lbl">Nota rápida do dia<textarea id="sd_nota" data-sdi="nota" data-day="${day}" placeholder="Para algo mais longo, use o diário.">${esc(e.nota || "")}</textarea></label>
      <div class="flbl">O resto do dia</div><div class="cxs">${ctxChips(dc)}</div><div class="row"><button type="button" class="btn sm" data-dnewday="${day}">${ic("pen")}Escrever no diário sobre ${day === TODAY ? "hoje" : "este dia"}</button></div>`)}
    ${panel("Últimos registros", `<div class="hscroll"><table class="dt"><thead><tr><th>Dia</th><th class="num">Sono</th><th class="num">Humor</th><th class="num">Energia</th><th class="num">Estresse</th><th>Treino</th><th class="num opt">Passos</th><th class="num opt">Peso</th></tr></thead><tbody>${last.map(([d, x]) => `<tr class="click${d === day ? " sel" : ""}" data-ckday="${d}" tabindex="0"><td>${fmtD(d)} <span class="muted">${DOWS[parse(d).getDay()]}</span></td><td class="num">${x.sono ?? ""}</td><td class="num">${x.humor ?? ""}</td><td class="num">${x.energia ?? ""}</td><td class="num">${x.estresse ?? ""}</td><td>${esc(x.treino || "")}${x.min ? ` · ${x.min}′` : ""}</td><td class="num opt">${x.passos ? num(x.passos, 0) : ""}</td><td class="num opt">${x.peso ?? ""}</td></tr>`).join("") || `<tr><td colspan="8" class="empty">Faça seu primeiro check-in ao lado.</td></tr>`}</tbody></table></div>`)}</div>`;
}

/* ---------------------------------------------------------------- Hábitos: marcar */
function pHabMarcar(R) {
  const days = []; for (let k = 13; k >= 0; k--) days.push(addDays(TODAY, -k));
  return `${kpiRow([kmini(acol("Saúde física"), "% da meta (média)", pct(R.habMeta), mlabel(R.mk), R.habMeta == null ? "" : R.habMeta >= .9 ? "good" : "warn"), kmini(acol("Finanças"), "Feitos no mês", sum(R.hab.map(h => h.feitos)), plural(R.hab.length, "hábito", "hábitos")), kmini(acol("Família"), "Maior sequência", R.hab.length ? Math.max(...R.hab.map(h => h.streak)) + " dias" : "–", R.hab.length ? esc([...R.hab].sort((a, b) => b.streak - a.streak)[0].nome) : ""), kmini("var(--crit)", "Abaixo da meta", R.hab.filter(h => h.st === "crit").length, "menos de 60% da meta", R.hab.some(h => h.st === "crit") ? "crit" : "good")])}
    ${panel("Últimas 2 semanas <small>toque para marcar</small>", `<div class="hscroll"><div class="hgrid" style="grid-template-columns:minmax(150px,1.4fr) repeat(14,minmax(26px,1fr)) 70px"><div></div>${days.map(d => `<div class="hd${d === TODAY ? " today" : ""}">${DOWS[parse(d).getDay()].slice(0, 1)}<br>${d.slice(8)}</div>`).join("")}<div class="hd">mês</div>
      ${R.hab.map(h => `<button type="button" class="hname" data-edit="habitos" data-id="${h.id}"><b>${esc(h.nome)}</b><small>${esc(ashort(h.area || ""))} · ${h.meta}×/sem · seq. ${h.streak}</small></button>${days.map(d => `<button type="button" class="tick${S.marks[h.id + "|" + d] ? " on" : ""}" style="--c:${acol(h.area)}" data-mark="${h.id}|${d}" aria-label="${esc(h.nome)} em ${fmtD(d)}" aria-pressed="${!!S.marks[h.id + "|" + d]}"></button>`).join("")}<div>${h.pm == null ? "" : pill(h.st, pct(h.pm))}</div>`).join("")}</div></div>${R.hab.length ? "" : `<div class="empty">Crie até 10 hábitos, cada um ligado a uma área da vida.</div>`}`, { act: addBtn("habitos", "Novo hábito") })}
    ${panel("Cumprimento por dia · 28 dias", strip(R.days28, "hab", "seq"))}`;
}

/* ---------------------------------------------------------------- Crescimento: carreira, aprendizado, lazer */
function pCarreira(R) {
  return `<div class="banner">${ic("brief")}<span>O plano completo (avaliação por grupo, trilhas, objetivos, geotecnia e biblioteca) fica no hub de <b>Carreira</b>; as competências são as mesmas daqui.</span><a class="btn sm primary" href="#carreira">Abrir o hub</a></div>${kpiRow([kmini(acol("Carreira"), "Candidaturas ativas", R.candAtivas, "aplicado, entrevista, teste ou proposta"), kmini(acol("Aprendizado"), "Competências", pct(R.compPct), "média do nível atual ÷ alvo"), kmini("var(--crit)", "Ações atrasadas", S.cand.filter(c => c.dataAcao && c.dataAcao < TODAY && !["Aceito", "Recusado", "Desisti"].includes(c.etapa)).length, "próximas ações das candidaturas")])}
    <div class="g2c">${panel("Competências <small>1 iniciante · 5 referência</small>", table("comp", S.comp, [["Competência", c => `<b>${esc(c.nome)}</b>`], ["Nível", c => `<span class="lvl">${"●".repeat(+c.atual || 0)}<s>${"○".repeat(Math.max(0, (+c.alvo || 0) - (+c.atual || 0)))}</s></span>`], ["Falta", c => (+c.alvo - +c.atual) || "", "num"]]), { act: addBtn("comp", "Nova") })}
    ${panel("Candidaturas", table("cand", [...S.cand].sort((a, b) => (b.data || "").localeCompare(a.data || "")), [["Empresa", c => `<b>${esc(c.empresa)}</b><div class="muted small">${esc(c.cargo)}</div>`], ["Etapa", c => esc(c.etapa)], ["Próxima ação", c => { const late = c.dataAcao && c.dataAcao < TODAY && !["Aceito", "Recusado", "Desisti"].includes(c.etapa); return `${esc(c.acao || "")}${c.dataAcao ? ` ${pill(late ? "crit" : diff(c.dataAcao, TODAY) <= 3 ? "warn" : "none", fmtD(c.dataAcao))}` : ""}`; }]]), { act: addBtn("cand", "Nova") })}</div>`;
}
function pAprend(R) {
  const est = [...S.estudo].sort((a, b) => b.data.localeCompare(a.data)), horas = t => sum(S.estudo.filter(e => e.item === t).map(e => e.horas)), and = S.aprend.filter(a => a.status === "Em andamento").length;
  return `${kpiRow([kmini(acol("Aprendizado"), "Estudo no mês", num(R.horasEst) + " h", `meta ${S.cfg.metaEstudo} h/mês`), kmini(acol("Propósito & espiritualidade"), "Livros no ano", R.livros, `meta ${S.cfg.metaLivros}`), kmini(acol("Carreira"), "Em andamento", and, and > 3 ? "muitos ao mesmo tempo dispersam" : "foco saudável", and > 3 ? "warn" : "good"), kmini(acol("Saúde mental"), "Sessões no mês", S.estudo.filter(e => mkey(e.data) === R.mk).length, mlabel(R.mk))])}
    <div class="g2c">${panel("O que estou aprendendo", table("aprend", [...S.aprend].sort((a, b) => (a.status !== "Em andamento") - (b.status !== "Em andamento")), [["Título", a => `<b>${esc(a.titulo)}</b><div class="muted small">${esc(a.tipo)} · ${esc(ashort(a.area || ""))}</div>`], ["Status", a => esc(a.status)], ["Progresso", a => { const p = a.status === "Concluído" ? 1 : +a.total ? clamp(+a.atual / +a.total) : 0; return `<div class="pbar"><span>${pct(p)}</span><div class="bt"><i style="width:${p * 100}%;background:${acol(a.area || "Aprendizado")}"></i></div></div>`; }], ["Horas", a => num(horas(a.titulo)), "num"]]), { act: addBtn("aprend", "Novo item") })}
    ${panel("Sessões de estudo", table("estudo", est, [["Dia", e => fmtD(e.data), "num"], ["Assunto", e => esc(e.item)], ["Horas", e => num(+e.horas), "num"]], { limit: 14 }), { act: addBtn("estudo", "Registrar") })}</div>`;
}
function pLazer(R) {
  return `<div class="banner">${ic("palette")}<span>Leitura, filmes, jogos, viagens, café, aviação, estudos e o lado existencial, cada um com um mentor, ficam na aba <b>Lazer</b>; o tempo que você registra lá entra aqui.</span><a class="btn sm primary" href="#lazer">Abrir o Lazer</a></div>${kpiRow([kmini(acol("Lazer & criatividade"), "Horas no mês", num(R.horasLaz) + " h", `meta ${Math.round(S.cfg.metaLazer * R.DR / 7)} h até agora`), kmini(acol("Amizades & social"), "Atividades", R.lazN, mlabel(R.mk)), kmini(acol("Saúde mental"), "Satisfação", R.lazSat == null ? "–" : num(R.lazSat) + "/5", "quanto recarregou"), kmini(acol("Finanças"), "Gasto com lazer", eur(R.lazCusto), R.horasLaz ? `${eur(R.lazCusto / R.horasLaz)} por hora` : "")])}
    <div class="g2c">${panel("Registro de lazer", table("lazer", [...S.lazer].sort((a, b) => b.data.localeCompare(a.data)), [["Dia", l => fmtD(l.data), "num"], ["Atividade", l => `<b>${esc(l.atividade)}</b>`], ["Categoria", l => esc(l.cat), "opt"], ["Horas", l => num(+l.horas), "num"], ["Satisfação", l => `<span class="stars">${"★".repeat(+l.sat || 0)}</span>`]], { limit: 16 }), { act: addBtn("lazer", "Registrar") })}
    ${panel("Lista de sonhos", table("sonhos", S.sonhos, [["Sonho", s => s.status === "Realizado" ? `<s class="muted">${esc(s.sonho)}</s>` : `<b>${esc(s.sonho)}</b>`], ["Status", s => pill(s.status === "Realizado" ? "good" : s.status === "Agendado" ? "warn" : "none", s.status)], ["Custo", s => s.custo ? eur(+s.custo) : "", "num opt"]]), { act: addBtn("sonhos", "Novo") })}</div>`;
}

/* ---------------------------------------------------------------- Relações: pessoas e contatos */
function pPessoas(R) {
  return `${kpiRow([kmini(acol("Amizades & social"), "Pessoas", S.pessoas.length, `família ${S.pessoas.filter(p => p.relacao === "Família").length} · amigos ${S.pessoas.filter(p => p.relacao === "Amizade").length}`), kmini("var(--good)", "Em dia", pct(R.relEmDia), "dentro da frequência desejada", R.relEmDia == null ? "" : R.relEmDia >= .8 ? "good" : "warn"), kmini("var(--crit)", "Atrasados", R.relAtras, R.relAtras ? "veja a lista" : "ninguém esquecido", R.relAtras ? "crit" : "good"), kmini(acol("Amor & parceria"), "Contatos no mês", R.contMes.length, `qualidade média ${num(avg(R.contMes.map(c => c.qual)))}/5`)])}
    ${panel("Pessoas <small>toque no nome para abrir a ficha</small>", `<div class="pgrid">${[...R.pes].sort((a, b) => b.ratio - a.ratio).map(p => { const st = diaryStats().people[p.nome]; return `<div class="pcard" style="--c:${acol(relArea(p.relacao))}"><button type="button" class="pc-h" data-ent="p|${esc(p.nome)}"><span class="pav">${esc(p.nome.replace(/[^\p{L}]/gu, "").slice(0, 2).toUpperCase() || "?")}</span><span><b>${esc(p.nome)}</b><small>${esc(p.relacao)} · a cada ${p.freq || "–"} dias</small></span></button><div class="pc-b">${pill(p.st, p.txt)}<span class="muted small">${p.ult ? `último ${relDay(p.ult)}` : "sem contato"}${st ? ` · ${plural(st.n, "menção", "menções")}` : ""}${p.prox && p.faltam <= 30 ? ` · aniversário ${relDay(p.prox)}` : ""}</span></div><div class="pc-a"><button type="button" class="btn sm" data-quickcont="${esc(p.nome)}">${ic("check")}Falei hoje</button><button type="button" class="vb" data-edit="pessoas" data-id="${p.id}" aria-label="Editar">${ic("edit")}</button></div></div>`; }).join("") || `<div class="empty">Cadastre as pessoas que importam e com que frequência quer falar com cada uma.</div>`}</div>`, { act: addBtn("pessoas", "Nova pessoa") })}`;
}
function pContatos(R) {
  return `${panel("Contatos registrados", table("contatos", [...S.contatos].sort((a, b) => b.data.localeCompare(a.data)), [["Dia", c => fmtD(c.data), "num"], ["Pessoa", c => `<button type="button" class="lnk" data-ent="p|${esc(c.pessoa)}">${esc(c.pessoa)}</button>`], ["Tipo", c => esc(c.tipo)], ["Qualidade", c => c.qual ? `${c.qual}/5` : "", "num"], ["Minutos", c => c.min || "", "num opt"]], { limit: 40 }), { act: addBtn("contatos", "Registrar contato") })}`;
}

/* ---------------------------------------------------------------- Casa e documentos */
function pCasa(R) {
  return `${kpiRow([kmini(acol("Casa & organização"), "Documentos a renovar", R.docs.filter(d => d.st === "warn" || d.st === "crit").length, `aviso com ${S.cfg.alertaDocs} dias`, R.docs.some(d => d.st === "crit") ? "crit" : ""), kmini("var(--crit)", "Rotinas atrasadas", R.rot.filter(r => r.st === "crit").length, `${R.rot.filter(r => r.st === "warn").length} nos próximos 7 dias`, R.rot.some(r => r.st === "crit") ? "crit" : "good"), kmini(acol("Finanças"), "Assinaturas por mês", eur(R.assMes, 2), `${eur(R.assMes * 12)} por ano`), kmini("var(--warn)", "Economia possível", eur(R.economia, 2), "por mês, em serviços de pouco uso", R.economia ? "warn" : "good")])}
    <div class="g3c">${panel("Documentos", table("docs", [...R.docs].sort((a, b) => (a.dias ?? 1e9) - (b.dias ?? 1e9)), [["Documento", d => `<b>${esc(d.doc)}</b><div class="muted small">${esc(d.acao || "")}</div>`], ["Validade", d => d.validade ? fmtDY(d.validade) : "", "num"], ["", d => pill(d.st, d.txt)]]), { act: addBtn("docs", "Novo") })}
    ${panel("Rotinas", `<div class="list">${[...R.rot].sort((a, b) => (a.dias ?? 1e9) - (b.dias ?? 1e9)).map(r => `<div class="li"><button type="button" class="t lnkb" data-edit="rotinas" data-id="${r.id}">${esc(r.rotina)}<div class="m">a cada ${r.freq} d · próxima ${fmtD(r.prox)}</div></button><div class="row">${pill(r.st, r.txt)}<button type="button" class="btn sm" data-done="${r.id}" title="Marcar como feita hoje">Feito</button></div></div>`).join("") || `<div class="empty">Cadastre limpezas, backups e revisões.</div>`}</div>`, { act: addBtn("rotinas", "Nova") })}
    ${panel("Assinaturas", table("assin", R.ass, [["Serviço", a => `<b>${esc(a.servico)}</b>`], ["Por mês", a => eur(a.mensal, 2), "num"], ["Uso", a => a.uso === "Baixo" ? pill("crit", "cancelar?") : esc(a.uso)]]), { act: addBtn("assin", "Nova") })}</div>`;
}

/* ---------------------------------------------------------------- lançamento e tarefa rápidos */
function quickLanc(v) {
  v = v.trim(); if (!v) return; let tipo = "Despesa"; if (v.startsWith("+")) { tipo = "Receita"; v = v.slice(1).trim(); } else if (v.startsWith(">")) { tipo = "Aporte"; v = v.slice(1).trim(); }
  const r = moneyCmd(tipo, v, { date: TODAY, area: "", humor: null }); if (!r.ok) { toast(r.err); return; }
  r.apply(); touch("lanc", { label: r.txt }); undoToast("Lançado: " + r.txt);
}
function quickTask(v) {
  v = v.trim(); if (!v) return; const r = CMD.tarefa.p(v, { date: TODAY, area: "", humor: null }); if (!r.ok) { toast(r.err); return; }
  r.apply(); touch("tarefas", { label: "Tarefa criada" }); undoToast(r.txt);
}
function quickHint(id, v) {
  const el = $("#" + id + "_h"); if (!el) return;
  if (!v.trim()) { el.className = "qhint"; el.textContent = el.dataset.def || el.textContent; return; }
  el.dataset.def ||= el.textContent;
  let r; if (id === "ql_in") { let t = v.trim(), tipo = "Despesa"; if (t.startsWith("+")) { tipo = "Receita"; t = t.slice(1); } else if (t.startsWith(">")) { tipo = "Aporte"; t = t.slice(1); } r = moneyCmd(tipo, t.trim(), { date: TODAY }); } else r = CMD.tarefa.p(v.trim(), { date: TODAY, area: "" });
  el.className = "qhint " + (r.ok ? "ok" : "bad"); el.textContent = r.ok ? "Vai registrar: " + r.txt : r.err;
}
