import asyncio, json
from harness import *
ok = 0; bad = 0
def chk(c, msg):
    global ok, bad
    if c: ok += 1; print("PASS", msg)
    else: bad += 1; print("FAIL", msg)
async def flush(pg):
    await pg.evaluate("flushSoon(0)"); await pg.wait_for_timeout(500)
async def main():
    async with async_playwright() as p:
        b, pg, errs = await open_page(p, w=1440)
        # ---------------- privacidade
        await pg.evaluate("location.hash='privacidade'"); await pg.wait_for_timeout(300)
        chk(await pg.evaluate("cryptoOk()"), "criptografia do navegador disponível (https)")
        await pg.fill("#cf_p1", "senha-forte-1"); await pg.fill("#cf_p2", "senha-forte-1")
        await pg.click("[data-act=cfcreate]"); await pg.wait_for_timeout(1500)
        chk(await pg.evaluate("!!S.priv.cofre && !!COFRE.key"), "cofre criado e aberto")
        chk(not await pg.evaluate("IS_EXAMPLE"), "criar o cofre transforma o exemplo em dados reais")
        eid = await pg.evaluate("S.diario.find(e => /Trattoria/.test(e.titulo)).id")
        plain = await pg.evaluate(f"S.diario.find(e => e.id === '{eid}').texto")
        await pg.evaluate("location.hash='diario'"); await pg.wait_for_timeout(300)
        await pg.evaluate(f"document.querySelector('#e_{eid} [data-act=dlock]').click()"); await pg.wait_for_timeout(800)
        e = await pg.evaluate(f"S.diario.find(e => e.id === '{eid}')")
        chk(bool(e.get("cifra")) and e["texto"] == "" and e["titulo"] == "", "entrada trancada: texto e título fora do estado")
        await flush(pg)
        store = await pg.evaluate("JSON.stringify(window.__store)")
        chk(plain[:30] not in store and "Trattoria com amigos" not in store, "texto aberto não chega ao banco depois de trancar")
        chk(await pg.locator(f"#e_{eid} .ent-body").inner_text() != "" and "Trattoria" in await pg.locator(f"#e_{eid}").inner_text(), "com o cofre aberto a entrada aparece normalmente")
        await pg.evaluate("cofreLock()"); await pg.wait_for_timeout(300)
        chk("Entrada trancada" in await pg.locator(f"#e_{eid}").inner_text(), "cofre fechado: cartão de cadeado no lugar do texto")
        await pg.evaluate("location.hash='privacidade'"); await pg.wait_for_timeout(300)
        await pg.fill("#cf_p", "errada"); await pg.click("[data-act=cfopen]"); await pg.wait_for_timeout(1500)
        chk(not await pg.evaluate("!!COFRE.key") and "incorreta" in await pg.locator(".pn").first.inner_text(), "senha errada não abre")
        await pg.fill("#cf_p", "senha-forte-1"); await pg.click("[data-act=cfopen]"); await pg.wait_for_timeout(1500)
        chk(await pg.evaluate(f"COFRE.plain.get('{eid}')?.titulo") == "Trattoria com amigos", "senha certa decifra")
        # trocar a senha recifra
        old = await pg.evaluate(f"S.diario.find(e => e.id === '{eid}').cifra.ct")
        await pg.evaluate("document.querySelector('details.ctx').open = true")
        await pg.fill("#cf_o", "senha-forte-1"); await pg.fill("#cf_n1", "outra-senha-2"); await pg.fill("#cf_n2", "outra-senha-2")
        await pg.click("[data-act=cfchange]"); await pg.wait_for_timeout(3500)
        chk(await pg.evaluate(f"S.diario.find(e => e.id === '{eid}').cifra.ct") != old, "trocar a senha recifra as entradas")
        await pg.evaluate("cofreLock()"); chk(await pg.evaluate("cofreUnlock('outra-senha-2')"), "nova senha abre")
        # setores sem IA + registro
        await pg.evaluate("location.hash='privacidade'"); await pg.wait_for_timeout(300)
        await pg.click("label:has(#pv_a1)"); await pg.wait_for_timeout(300)
        chk(await pg.evaluate("S.priv.semIA.includes('Saúde mental')"), "Saúde mental marcada como sem IA")
        await pg.evaluate("location.hash='mentor.men'"); await pg.wait_for_timeout(300)
        await pg.evaluate("askMentor('men', 'oi')"); await pg.wait_for_timeout(300)
        chk(await pg.evaluate("!window.__calls.some(c => c.kind === 'sample')"), "mentor de setor bloqueado não chama a IA")
        n0 = await pg.evaluate("S.auditoria.length")
        await pg.evaluate("location.hash='mentor.conselho'"); await pg.wait_for_timeout(300)
        await pg.evaluate("askMentor('conselho', 'Como foi a semana?')"); await pg.wait_for_timeout(2500)
        prompt = await pg.evaluate("JSON.stringify(window.__calls.filter(c => c.kind === 'sample').at(-1)?.input || '')")
        chk("setor privado" in prompt, "Conselho recebe a área bloqueada como setor privado")
        chk("#terapia" not in prompt and "terapia" not in prompt.lower(), "tema só de entrada #privado não sai no pedido")
        chk("sozinho" not in prompt, "entrada marcada sem IA não sai no pedido")
        chk("Trattoria" not in prompt, "entrada trancada não sai no pedido")
        last = await pg.evaluate("S.auditoria[0]")
        chk(await pg.evaluate("S.auditoria.length") == n0 + 1 and last["recurso"] == "Conselho" and last["status"] == "ok", "registro de leitura ganhou a chamada do Conselho")
        priv_ids = await pg.evaluate("S.diario.filter(e => !aiAllowed(e)).map(e => e.id)")
        chk(not set(priv_ids) & set(last["ent"]), "registro não lista entradas protegidas como lidas")
        chk(last["bloq"] >= 1, f"registro conta entradas barradas ({last['bloq']})")
        tools = await pg.evaluate("window.__calls.filter(c => c.kind === 'toolerr').map(c => c.m)")
        chk(any("privado" in t for t in tools), "ferramenta cruzar recusa métrica de setor privado")
        await pg.evaluate("location.hash='privacidade'"); await pg.wait_for_timeout(300)
        await pg.click("tr[data-pvdet]"); await pg.wait_for_timeout(300)
        chk(await pg.locator("#dlg[open]").count() == 1 and "entradas que foram enviadas" in (await pg.locator("#dlg").inner_text()).lower(), "detalhe do registro abre")
        await pg.keyboard.press("Escape")
        await pg.click("[data-act=pvcsv]"); await pg.wait_for_timeout(300)
        chk(await pg.evaluate("window.__saved.some(s => /registro-ia/.test(s.filename))"), "registro exporta CSV")
        await pg.click("label:has(#pv_a1)"); await pg.wait_for_timeout(200)
        # editor: não enviar à IA
        await pg.evaluate("location.hash='diario'"); await pg.wait_for_timeout(200)
        await pg.evaluate("openComposer()"); await pg.wait_for_timeout(200)
        await pg.fill("#dz_texto", "Teste sem IA #mente"); await pg.check("#dz_semia"); await pg.click("[data-act=dzsave]"); await pg.wait_for_timeout(400)
        chk(await pg.evaluate("S.diario.find(e => e.texto === 'Teste sem IA #mente')?.semIA === true"), "editor salva entrada sem IA")
        await pg.evaluate("openComposer()"); await pg.wait_for_timeout(200)
        await pg.fill("#dz_texto", "Segredo trancado na hora\n/humor 4"); await pg.check("#dz_lock"); await pg.wait_for_timeout(200)
        await pg.click("[data-act=dzsave]"); await pg.wait_for_timeout(900)
        z = await pg.evaluate("S.diario.find(e => e.cifra && COFRE.plain.get(e.id)?.texto?.startsWith('Segredo'))")
        chk(z is not None and z["texto"] == "" and z["aplicados"] == ["/humor 4"], "entrada nova trancada no editor, com o comando aplicado antes de cifrar")
        await flush(pg)
        chk("Segredo trancado" not in await pg.evaluate("JSON.stringify(window.__store)"), "entrada nova trancada não vai aberta para o banco")
        # ---------------- captura
        await pg.evaluate("location.hash='hoje'"); await pg.wait_for_timeout(300)
        txt = "Dormi 7h e meia, corri 30 min com o Lucas. Almocei com o Marco, gastei 18 euros. Preciso ligar para o banco até sexta. Meditei e li 20 páginas."
        await pg.fill("#hj_cap", txt); await pg.wait_for_timeout(600)
        lines = await pg.evaluate("CAP.items.map(x => [x.line, x.on, x.ok])")
        L = [l[0] for l in lines]
        for want in ["/sono 7,5", "/treino Corrida 30", "/contato @Lucas Encontro 30", "/contato @Marco Encontro", "/habito Meditar 10 min", "/habito Ler 20 páginas"]:
            chk(want in L, f"captura reconhece {want}")
        chk(any(l.startswith("/gasto 18 ") and "almoço" in l for l in L), f"captura reconhece o gasto com descrição ({[l for l in L if l.startswith('/gasto')]})")
        chk(any(l.startswith("/tarefa ligar para o banco") for l in L), "captura reconhece a tarefa")
        chk(all(l[2] for l in lines), "todos os registros reconhecidos passam na validação")
        nl0 = await pg.evaluate("S.lanc.length")
        await pg.click(".capcard [data-act=capsave]"); await pg.wait_for_timeout(500)
        chk(await pg.evaluate("S.saude[TODAY].sono") == 7.5 and await pg.evaluate("S.saude[TODAY].treino") == "Corrida", "sono e treino gravados no dia")
        g = await pg.evaluate("S.lanc.at(-1)")
        chk(await pg.evaluate("S.lanc.length") == nl0 + 1 and g["valor"] == 18 and g["cat"] == "Restaurantes & cafés", "gasto gravado e categorizado")
        chk(await pg.evaluate("S.tarefas.some(t => /ligar para o banco/i.test(t.tarefa) && t.prazo)"), "tarefa criada com prazo")
        chk(await pg.evaluate("!!S.marks[S.habitos.find(h => /Meditar/.test(h.nome)).id + '|' + TODAY]"), "hábito marcado")
        ent = await pg.evaluate("S.diario.find(e => e.origem === 'captura')")
        chk(ent and "@Marco" in ent["texto"] and "@Lucas" in ent["texto"] and len(ent["aplicados"]) >= 8, "entrada da captura com menções e comandos já aplicados")
        chk(await pg.evaluate("CAP.text") == "", "captura limpa depois de salvar")
        # ontem + valores com milhar
        await pg.click("[data-act=cap]"); await pg.wait_for_timeout(200)
        await pg.fill("#cap_txt", "Ontem paguei 1.250 de aluguel e recebi 2.450,50 de salário"); await pg.wait_for_timeout(600)
        L2 = await pg.evaluate("CAP.items.map(x => x.line)")
        chk(await pg.evaluate("CAP.data") == await pg.evaluate("addDays(TODAY, -1)"), "“ontem” muda o dia da captura")
        chk(any(l.startswith("/gasto 1250 ") for l in L2) and any(l.startswith("/receita 2450,5 ") for l in L2), f"valores com separador de milhar ({L2})")
        # IA organiza
        await pg.click("#capf [data-act=capai]"); await pg.wait_for_timeout(800)
        ai = await pg.evaluate("CAP.items.map(x => [x.line, x.src, x.ok])")
        chk(len(ai) == 3 and all(x[1] == "ia" for x in ai), f"IA substitui pela lista dela e descarta comando inválido ({ai})")
        chk("Quanto tempo durou o almoço?" in await pg.locator("#capf").inner_text(), "dúvidas da IA aparecem")
        chk(await pg.evaluate("S.auditoria[0].recurso") == "Captura", "captura com IA entra no registro")
        await pg.click("#capf [data-act=capsave]"); await pg.wait_for_timeout(400)
        chk(await pg.evaluate("S.diario.at(-1).texto.startsWith('Almocei com @Marco')") or await pg.evaluate("S.diario.some(e => e.texto.startsWith('Almocei com @Marco'))"), "entrada organizada pela IA salva")
        # ---------------- experimentos
        await pg.evaluate("location.hash='exp'"); await pg.wait_for_timeout(300)
        st = await pg.evaluate("(() => { const A = [3,3,4,3,4,3,3,4,3,3], B = A.map(x => x + 1); const s = expStats(A, B, 7), z = expStats(A, A.slice().reverse(), 7); return [s.d, s.lo, s.hi, s.p, z.lo, z.hi]; })()")
        chk(abs(st[0] - 1) < 1e-9 and st[1] > 0 and st[3] < 0.01, f"estatística: efeito real tem intervalo acima de zero e p baixo ({st[:4]})")
        chk(st[4] <= 0 <= st[5], "estatística: sem efeito, o intervalo inclui zero")
        sch = await pg.evaluate("(() => { const x = { id: 'tt', inicio: TODAY, dias: 28, bloco: 7, desenho: 'alternado', seed: 5 }; const s = Object.values(expSchedule(x)); return [s.length, s.filter(c => c === 'A').length, s.filter(c => c === 'B').length]; })()")
        chk(sch == [28, 14, 14], f"cronograma equilibrado: {sch}")
        await pg.click("[data-act=expnew]"); await pg.wait_for_timeout(200)
        await pg.fill("#ex_titulo", "Teste de leitura"); await pg.fill("#ex_int", "Ler 20 minutos antes de dormir")
        await pg.select_option("#ex_met", "sono"); await pg.select_option("#ex_lag", "1"); await pg.click("#exok"); await pg.wait_for_timeout(300)
        x = await pg.evaluate("S.experimentos.at(-1)")
        chk(x["titulo"] == "Teste de leitura" and x["metrica"] == "sono" and x["defasagem"] == 1 and x["status"] == "ativo", "experimento criado pelo formulário")
        await pg.evaluate("location.hash='hoje'"); await pg.wait_for_timeout(300)
        act = await pg.evaluate("S.experimentos.filter(x => x.status === 'ativo' && expSchedule(x)[TODAY]).length")
        chk(await pg.locator(".hjexp").count() == act, f"Hoje mostra os experimentos do dia ({act})")
        btn = pg.locator(".hjexp [data-expad]").first
        dv = await btn.get_attribute("data-expad"); await btn.click(); await pg.wait_for_timeout(300)
        xid, v = dv.split("|")[0], int(dv.split("|")[1])
        chk(await pg.evaluate(f"S.experimentos.find(x => x.id === '{xid}').adesao[TODAY]") == v, "marcar fiz/não fiz no Hoje")
        await pg.evaluate("location.hash='exp'"); await pg.wait_for_timeout(300)
        await pg.click("[data-expsel=ex2]"); await pg.wait_for_timeout(300)
        dbg = await pg.evaluate("[EXP.sel, document.querySelectorAll('.expdet').length, document.querySelectorAll('.expdet svg.chart').length, (document.querySelector('.expdet')?.innerText || '').slice(0, 300)]")
        chk(await pg.locator(".expdet svg.chart").count() >= 1 and "diferença com" in (await pg.locator(".expdet").inner_text()).lower(), f"análise com gráfico e intervalo {dbg}")
        nd = await pg.evaluate("S.diario.length")
        await pg.click("[data-expend=ex2]"); await pg.wait_for_timeout(400)
        x2 = await pg.evaluate("S.experimentos.find(x => x.id === 'ex2')")
        chk(x2["status"] == "concluido" and x2["conclusao"], "encerrar guarda a conclusão")
        chk(await pg.evaluate("S.diario.length") == nd + 1 and await pg.evaluate("S.diario.at(-1).texto.includes('#experimento')"), "resultado vai para o diário")
        chk(await pg.evaluate("mget('fis').mem.some(m => m.origem === 'experimento') || mget('men').mem.some(m => m.origem === 'experimento')"), "resultado vai para a memória do mentor da área")
        chk(await pg.locator("[data-expidea]").count() >= 1, "ideias de experimento a partir dos cruzamentos")
        chk(not errs, f"sem erros no console {errs}")
        await b.close()
    print(f"\n{ok}/{ok + bad} passaram")
asyncio.run(main())
