/* ================================================================ capa, missão e manual de cada aba + Mapa do Atlas
   A capa é uma ilustração vetorial desenhada aqui (sem fotos externas: a página pode não ter acesso à internet e fica leve).
   Cada aba tem: cor, cena, missão (por que existe), o que resolve, de onde vêm e para onde vão os dados, e um manual curto. */
const TAB_INFO = {
  visao: { cor: "var(--accent)", cena: "constel", foto: "Céu ao entardecer com constelações ligadas por linhas finas", missao: "O retrato do mês em uma tela: cada área da vida com nota, tendência e o que pede atenção.", resolve: "Saber em 30 segundos se o mês vai bem, sem abrir dez abas.", entra: "Tudo o que você registra nas outras abas.", sai: "Atalhos para a área que mais precisa de você.", manual: ["Escolha o mês no topo (‹ ›) para ver meses passados.", "Clique numa área para abrir o relatório dela.", "Os números vêm dos registros; a Roda da Vida mostra a sua percepção ao lado."] },
  hoje: { cor: "var(--warn)", cena: "sunrise", foto: "Janela com luz da manhã sobre telhados de Turim e os Alpes ao fundo", missao: "Um resumo do momento: tempo lá fora, uma frase que conversa com o seu dia real, ideias para sair da rotina e o que vence hoje.", resolve: "Começar o dia sabendo o que vestir, o que importa e uma coisa boa para fazer, sem ler dez aplicativos.", entra: "Clima da sua cidade, notícias positivas, seu humor, energia, tempo livre e orçamento.", sai: "Tarefas do dia, Painel do dia para registrar, Lazer para as ideias.", manual: ["Responda as 4 perguntas rápidas em “Como você está agora?”; tudo abaixo se ajusta.", "O clima vem da internet para a cidade escolhida; sem conexão, marque o tempo à mão.", "As ideias mudam com clima, energia, tempo e dinheiro. “Outra ideia” troca uma de cada vez.", "Para registrar sono, humor, gastos e hábitos, use o Painel do dia."] },
  painel: { cor: "var(--accent)", cena: "waves", foto: "Microfone de mesa ao lado de um caderno aberto", missao: "Registrar o essencial do dia em um minuto, por texto ou voz, e conferir antes que vá para as abas.", resolve: "Registro diário que não acontece porque dá trabalho.", entra: "O que você fala ou escreve.", sai: "Saúde, Finanças, Hábitos, Jornada, Lazer, Diário e Tarefas.", manual: ["Fale ou escreva o dia no campo grande; os campos se preenchem sozinhos.", "Use o microfone de um campo para ditar só aquele valor.", "“Revisar e salvar” mostra o que é novo, o que substitui e o que parece repetido.", "Um único Desfazer volta tudo o que o painel salvou."] },
  rotina: { cor: "var(--a-car)", cena: "calendar", foto: "Agenda de papel aberta na semana, com blocos coloridos de meia hora e uma xícara de café", missao: "Desenhar o dia em blocos de 30 minutos: o que você planeja, o que já está na agenda e o que de fato fez.", resolve: "Dias que somem em tarefas soltas e planos que não cabem no relógio.", entra: "Seus blocos, a Agenda (e o Google Calendar) e as tarefas com prazo.", sai: "Idiomas (o plano desconta os blocos), Hoje (a rotina do dia).", manual: ["Escolha Dia, Semana ou Mês no topo; ‹ › mudam o período e Hoje volta para hoje.", "No calendário pequeno, clique num dia para ver as horas dele, ou no número da semana para ver a semana inteira.", "Clique numa meia hora para criar um bloco de 30 min; arraste por várias para criar um bloco maior.", "Clique num bloco para editar, marcar como feito ou excluir. “Repetir” cria rotinas diárias, de dias úteis ou semanais.", "Os compromissos da Agenda e do Google aparecem tracejados: são editados na Agenda."] },
  diario: { cor: "var(--a-men)", cena: "notebook", foto: "Caderno de capa de couro aberto, caneta tinteiro e xícara de café", missao: "O lugar das palavras: o que aconteceu, o que você sentiu e o que aprendeu, ligado às pessoas, temas e metas.", resolve: "Memória do que viveu e padrões que só aparecem escritos.", entra: "Seus textos, @pessoas, #temas e comandos “/”.", sai: "Cruzamentos, Capítulos, mentores (se você permitir).", manual: ["@ menciona uma pessoa, # marca um tema, [[ liga a uma meta ou tarefa.", "Linhas começando com / registram dados (ex.: /gasto 12 almoço).", "Em Perguntar, busque por significado: “quando me senti sozinho?”."] },
  jornada: { cor: "var(--jp-med)", cena: "lotus", foto: "Flor de lótus num lago parado ao amanhecer", missao: "Cultivar a vida interior em quatro caminhos (Espiritismo, meditação, Taoísmo e Budismo) e a bússola moral que orienta as decisões.", resolve: "Prática espiritual que fica solta, sem continuidade nem reflexão.", entra: "Sessões de prática, reflexões, exame da noite, decisões.", sai: "Métricas de prática nos Cruzamentos e o Hoje.", manual: ["Comece pela aba de um pilar e registre a estação em que você está.", "Saúde espiritual é o jardim: cada árvore cresce com um pilar, o rio com o exame da noite, e o templo com as inclinações que você trabalha.", "Na mandala, toque numa pétala para explorar; as camadas mostram ritmo e evolução.", "Práticas guarda programas guiados e sessões (com estado antes e depois).", "A Bússola moral tem o exame da noite e as oito perguntas antes de decidir."] },
  mentores: { cor: "var(--accent)", cena: "spark", foto: "Mesa de conversa com duas cadeiras e luz suave", missao: "Um conselheiro por área, que lê os seus dados (só os que você liberar) e lembra do que vocês combinaram.", resolve: "Conselho genérico que ignora a sua situação real.", entra: "Os dados das áreas liberadas em Privacidade.", sai: "Tarefas, metas e hábitos que você aceitar.", manual: ["Escolha o mentor da área; o Conselho vê todas.", "As propostas só viram tarefa quando você aceita.", "Privacidade controla o que cada mentor pode ler."] },
  cruz: { cor: "var(--a-apr)", cena: "scatter", foto: "Fios coloridos se cruzando num tear", missao: "Descobrir o que anda junto na sua vida: sono e humor, gastos e estresse, prática e foco.", resolve: "Intuições sobre si que nunca são conferidas.", entra: "As séries diárias de todas as abas.", sai: "Ideias para Experimentos.", manual: ["Escolha duas métricas ou deixe o Atlas procurar as relações mais fortes.", "Correlação não é causa: teste em Experimentos antes de mudar a rotina."] },
  fin: { cor: "var(--a-fin)", cena: "growth", foto: "Mesa com caderno de contas, calculadora e moedas de euro e real", missao: "Saber para onde vai o dinheiro, quanto sobra e se o futuro está sendo construído, em euro e em real.", resolve: "Fim de mês sem saber o que aconteceu e decisões grandes sem número.", entra: "Lançamentos, orçamento, patrimônio, salário (Carreira), contas da casa.", sai: "Futuro financeiro, Visão geral, mentor de Finanças.", manual: ["Lançamentos: registre ou importe extratos; categorias aprendem com você.", "Orçamento & patrimônio: teto por categoria, assinaturas e o patrimônio do fim do mês.", "Futuro financeiro: reserva, TFR e previdência com as contas feitas.", "Itália & Brasil: contas dos dois países e o total em euro na cotação do dia."] },
  "fin.futuro": { missao: "Três camadas de segurança: a reserva para imprevistos, o TFR que se acumula com o seu contrato e a previdência para a aposentadoria. Cada uma com conta feita e um próximo passo." },
  "fin.vida": { missao: "Viver na Itália com vínculos no Brasil: prazos de documentos dos dois países e o custo mensal de cada lado, somado em euro com a cotação do dia." },
  saude: { cor: "var(--a-fis)", cena: "pulse", foto: "Tênis de corrida num banco de parque com luz da manhã", missao: "Corpo e mente em números simples: sono, treino, passos, humor, energia e estresse.", resolve: "Cansaço sem causa aparente e metas de saúde que não são acompanhadas.", entra: "Painel do dia, Apple Health, Google Fit.", sai: "Cruzamentos, Radar, Visão geral.", manual: ["Registre pelo Painel do dia; o Check-in aqui serve para corrigir dias passados.", "Metas de sono, passos e treinos ficam em Ajustes."] },
  hab: { cor: "var(--a-men)", cena: "checks", foto: "Calendário de parede com dias marcados em sequência", missao: "Os pequenos atos repetidos que constroem quem você quer ser.", resolve: "Boas intenções que somem na terceira semana.", entra: "Marcações (aqui, no Painel ou por texto).", sai: "Sequências, Cruzamentos, Visão geral.", manual: ["Crie poucos hábitos com meta de dias por semana.", "Marque no Painel do dia; aqui você vê a semana e corrige."] },
  metas: { cor: "var(--a-car)", cena: "target", foto: "Trilha de montanha com uma bandeira no cume", missao: "Transformar intenções em metas mensuráveis e tarefas com prazo.", resolve: "Listas enormes sem prioridade e metas sem número.", entra: "Metas, tarefas, objetivos da Carreira, propostas dos mentores.", sai: "Hoje (o que vence), Fechamento da semana.", manual: ["Uma meta precisa de número e prazo.", "Ligue tarefas a metas para ver o avanço real."] },
  pessoas: { cor: "var(--a-ami)", cena: "people", foto: "Mesa de jantar com várias mãos passando pratos", missao: "Cuidar das relações que importam: quem você vê, quando falou pela última vez e quem está ficando distante.", resolve: "Amizades e família esquecidas sem perceber.", entra: "Pessoas, contatos, menções no diário.", sai: "Alertas de contato, Rede profissional (pessoas de trabalho).", manual: ["Defina de quanto em quanto tempo quer falar com cada pessoa.", "Pessoas de trabalho (relação Trabalho ou Mentoria) aparecem na Rede profissional da Carreira."] },
  cresc: { cor: "var(--a-apr)", cena: "sprout", foto: "Muda de planta brotando num vaso perto de livros", missao: "Aprender e sonhar: livros, cursos, horas de estudo e as experiências que você quer viver.", resolve: "Cursos comprados e não terminados, sonhos sem plano.", entra: "Itens de aprendizado, sessões de estudo (também as de Idiomas).", sai: "Visão geral, Capítulos.", manual: ["Cadastre o que está estudando e registre as horas.", "Os idiomas têm aba própria; as sessões deles aparecem aqui também."] },
  carreira: { cor: "var(--a-car)", cena: "road", foto: "Rodovia em curva num vale alpino, com uma ponte de concreto ao fundo", missao: "Desenvolvimento profissional com direção: onde você está, aonde quer chegar, o que sabe, quem conhece e o que fazer nesta semana.", resolve: "Carreira levada pelo acaso, conhecimento técnico que se perde e contatos que esfriam.", entra: "Seu perfil e cargo, competências, projetos, notas técnicas, contatos de trabalho.", sai: "Metas e tarefas, Finanças (salário, TFR), Idiomas (inglês técnico).", manual: ["Panorama: o resumo e o próximo passo.", "Caderno técnico: anote fórmulas, normas e lições de obra; busque quando precisar.", "Rede profissional: contatos de trabalho com cadência e oportunidades em andamento.", "Plano de ação: cada gap vira ação com prazo."] },
  "carreira.caderno": { missao: "O seu manual de engenharia, escrito por você: fórmulas, normas, procedimentos e lições de obra que você não quer reaprender do zero." },
  "carreira.rede": { missao: "Relações profissionais cuidadas com intenção: quem você conhece, quando falou pela última vez e que oportunidades estão em andamento." },
  lazer: { cor: "var(--a-laz)", cena: "palette", foto: "Mesa com xícara de café, livro aberto e controle de videogame", missao: "Tempo livre com qualidade: o que você lê, assiste, joga, prepara e explora, com um mentor para cada tema.", resolve: "Fim de semana no automático e hobbies que não evoluem.", entra: "Gostos, registros de lazer, ideias do Hoje.", sai: "Sugestões no seu nível, Visão geral.", manual: ["Escolha um tema e converse com o mentor dele.", "As ideias para sair da rotina do Hoje usam os seus gostos daqui."] },
  idiomas: { cor: "var(--a-apr)", cena: "bubbles", foto: "Duas xícaras numa mesa de café com um caderno de vocabulário em inglês e italiano", missao: "Inglês em primeiro lugar e italiano em seguida, com um percurso para o seu nível e um plano que cabe na sua semana real.", resolve: "Estudar sem saber se está avançando e planos que ignoram a agenda.", entra: "Seu nível, meta, disponibilidade por dia e a Agenda.", sai: "Sessões no Crescimento, tarefas da semana.", manual: ["Defina o nível atual e a meta de cada idioma (se não sabe, faça um teste gratuito indicado).", "Informe quantos minutos tem por dia e a janela de estudo; o plano desconta compromissos da Agenda.", "Registre cada sessão: o progresso e a previsão de chegada se atualizam."] },
  casa: { cor: "var(--a-fam)", cena: "house", foto: "Sala clara com plantas, estante e uma lista de compras presa na geladeira", missao: "A casa como espaço físico e como conta: limpeza em dia, compras organizadas, contas pagas no prazo e documentos à mão.", resolve: "Multas por atraso, faxina que só acontece em crise e documentos que ninguém acha.", entra: "Rotinas de limpeza, lista de compras, contas e documentos.", sai: "Lançamentos em Finanças ao pagar uma conta, alertas no Hoje.", manual: ["Limpeza: rotinas do leve (diário) ao pesado (mensal/sazonal); marque ao fazer.", "Compras: itens fixos voltam toda semana; marque ao pôr no carrinho.", "Contas: calendário dos vencimentos; “Paguei” pode lançar em Finanças.", "Documentos: contratos, contas anuais e onde estão guardados."] },
  roda: { cor: "var(--a-car)", cena: "wheel", foto: "Roda de bicicleta antiga encostada num muro colorido", missao: "Sua percepção de cada área, mês a mês, ao lado do que os dados dizem.", resolve: "Diferença entre como a vida parece e como ela está.", entra: "Notas de 0 a 10, revisão mensal.", sai: "Visão geral, Capítulos.", manual: ["No fim do mês, dê uma nota a cada área e preencha a revisão."] },
  semana: { cor: "var(--accent)", cena: "calendar", foto: "Agenda semanal aberta com três prioridades sublinhadas", missao: "Fechar a semana em 15 minutos: números, destaques, o que foi cumprido e três prioridades.", resolve: "Semanas que passam sem aprendizado.", entra: "Tudo da semana.", sai: "Prioridades no Hoje, carta da semana.", manual: ["Na segunda (ou domingo à noite), siga os passos de cima para baixo."] },
  radar: { cor: "var(--warn)", cena: "radar", foto: "Farol à noite com o feixe de luz varrendo o mar", missao: "Alertas antes que o problema chegue, com a evidência do seu histórico.", resolve: "Descobrir tarde que o orçamento estourou ou que o sono caiu.", entra: "Séries diárias e orçamento.", sai: "Hoje, mentores.", manual: ["Marque se o alerta foi útil ou alarme falso: o Radar aprende a taxa de acerto."] },
  exp: { cor: "var(--a-apr)", cena: "flask", foto: "Bancada com frascos de vidro e um caderno de anotações", missao: "Testar uma mudança em você com método: antes e depois, ou dias alternados.", resolve: "Mudanças de rotina sem saber se funcionaram.", entra: "Uma hipótese e a métrica.", sai: "Efeito e incerteza.", manual: ["Escolha uma métrica dos Cruzamentos e o desenho do teste; registre normalmente."] },
  capitulos: { cor: "var(--a-apr)", cena: "book", foto: "Estante com livros de lombadas datadas por ano", missao: "As fases da sua vida, detectadas nos dados, e o livro do ano em PDF.", resolve: "Memória de longo prazo que se apaga.", entra: "Diário e séries.", sai: "Livro em PDF.", manual: ["Revise os capítulos sugeridos e dê nomes a eles."] },
  dupla: { cor: "var(--a-amo)", cena: "duo", foto: "Duas xícaras lado a lado numa varanda", missao: "Diário, orçamento e metas em comum com quem você escolher, cada um com seus dados privados.", resolve: "Planejar a dois sem misturar tudo.", entra: "O que cada um decide compartilhar.", sai: "Orçamento e metas comuns.", manual: ["Convide a pessoa e escolha o que compartilhar."] },
  dados: { cor: "var(--muted)", cena: "table", foto: "Planilha impressa organizada com marcadores coloridos", missao: "Todos os registros como planilha: editar, filtrar, alterar em massa, importar e exportar.", resolve: "Corrigir dados sem procurar aba por aba.", entra: "Tudo.", sai: "Tudo.", manual: ["Escolha a tabela, filtre e clique numa linha para editar.", "Selecione várias linhas para alterar ou apagar em massa; Exportar gera CSV."] },
  integ: { cor: "var(--muted)", cena: "plug", foto: "Cabos conectados num painel organizado", missao: "Notion, agenda, Apple Health, Google Fit e extratos bancários, nos dois sentidos onde dá.", resolve: "Digitar à mão o que já existe em outro lugar.", entra: "Arquivos e conectores.", sai: "Backup e envios.", manual: ["Importe um arquivo ou conecte o Notion; o Atlas mostra o que vai entrar antes."] },
  privacidade: { cor: "var(--muted)", cena: "shield", foto: "Cofre antigo com a porta entreaberta", missao: "Você decide o que a IA lê: cofre com senha, setores fora da IA e o registro de cada leitura.", resolve: "Usar IA sem expor o que não quer.", entra: "Suas escolhas.", sai: "Limites para mentores e captura.", manual: ["Tire áreas da IA e tranque entradas do diário com senha."] },
  ajustes: { cor: "var(--muted)", cena: "sliders", foto: "Mesa de som com controles deslizantes", missao: "Metas, listas, áreas, mentores e aparência do Atlas.", resolve: "Um sistema que não se adapta a você.", entra: "Suas preferências.", sai: "Todo o Atlas.", manual: ["Comece pelas metas (sono, poupança, passos) e pelas listas de categorias."] },
  mapa: { cor: "var(--accent)", cena: "constel", foto: "Mapa antigo aberto sobre a mesa com uma bússola", missao: "A estrutura do Atlas: para que serve cada aba, de onde vem e para onde vai cada dado, e o que ainda falta.", resolve: "Não saber onde registrar algo ou onde encontrar.", entra: "", sai: "", manual: ["Use como índice: cada linha leva à aba.", "As setas mostram para onde os dados seguem."] },
};
/* cenas da capa: formas simples, com a cor da aba */
function coverScene(k) {
  const hills = `<path class="h2" d="M0 92 C90 70 170 96 260 80 S430 62 600 84 V112 H0Z"/><path class="h1" d="M0 102 C120 88 220 108 330 96 S500 86 600 100 V112 H0Z"/>`;
  const S2 = {
    sunrise: `<circle class="a" cx="470" cy="88" r="44"/><circle class="b" cx="470" cy="88" r="26"/><path class="m" d="M330 112 L410 50 L450 78 L500 36 L600 104 V112Z"/>${hills}`,
    road: `<path class="m" d="M300 112 L380 44 L430 70 L500 30 L600 90 V112Z"/><path class="rd" d="M360 112 C420 90 430 70 520 58 L600 52"/><path class="rl" d="M360 112 C420 90 430 70 520 58 L600 52"/><path class="br" d="M410 112 V84 M560 112 V84 M400 84 Q485 40 570 84"/>`,
    house: `<path class="b" d="M420 112 V62 L490 22 L560 62 V112Z"/><rect class="w" x="448" y="72" width="22" height="20" rx="2"/><rect class="w" x="508" y="72" width="22" height="20" rx="2"/><path class="a" d="M400 112 q12 -34 26 0Z M572 112 q10 -26 22 0Z"/>${hills}`,
    growth: `${[0, 1, 2, 3, 4].map(i => `<rect class="${i % 2 ? "a" : "b"}" x="${400 + i * 36}" y="${92 - i * 16}" width="24" height="${20 + i * 16}" rx="3"/>`).join("")}<circle class="w" cx="380" cy="40" r="14"/><circle class="a" cx="352" cy="58" r="10"/>`,
    bubbles: `<rect class="b" x="380" y="18" width="120" height="52" rx="14"/><path class="b" d="M402 68 l-6 18 l22 -18Z"/><rect class="a" x="460" y="50" width="120" height="52" rx="14"/><text class="tx" x="440" y="52" text-anchor="middle">EN</text><text class="tx" x="520" y="84" text-anchor="middle">IT</text>`,
    lotus: `<circle class="a" cx="500" cy="34" r="16"/><path class="b" d="M480 96 C470 70 490 54 500 46 C510 54 530 70 520 96Z"/><path class="a" d="M500 96 C470 92 448 74 446 60 C470 62 490 76 500 96Z M500 96 C530 92 552 74 554 60 C530 62 510 76 500 96Z"/>${hills}`,
    notebook: `<rect class="b" x="410" y="18" width="150" height="86" rx="6"/><path class="ln" d="M432 42 H540 M432 58 H540 M432 74 H510"/><path class="a" d="M560 10 l14 8 l-60 96 l-14 -8Z"/>`,
    waves: `${[0, 1, 2, 3, 4, 5, 6].map(i => { const h = [20, 44, 70, 52, 84, 40, 26][i]; return `<rect class="${i % 2 ? "a" : "b"}" x="${410 + i * 22}" y="${60 - h / 2}" width="12" height="${h}" rx="6"/>`; }).join("")}`,
  };
  const ICONSC = { constel: "spark", pulse: "pulse", checks: "repeat", target: "target", people: "users", sprout: "sprout", palette: "palette", wheel: "wheel", calendar: "week", radar: "radar", flask: "flask", book: "chapters", duo: "duo", table: "table", plug: "plug", shield: "shield", sliders: "sliders", scatter: "scatter", spark: "spark" };
  if (S2[k]) return S2[k];
  return `<circle class="a" cx="500" cy="56" r="46"/>${hills}<g class="ic" transform="translate(470 26) scale(2.5)">${ICONS[ICONSC[k] || "grid"]}</g>`;
}
const tabKey = () => PAGE === "mentor" ? "mentores" : PAGE;
function tabInfo() { const base = TAB_INFO[tabKey()]; if (!base) return null; const sub = TAB_INFO[`${tabKey()}.${SUB}`]; return { ...base, ...(sub || {}) }; }
function tabHead() {
  const T = tabInfo(); if (!T) return "";
  let open = false; try { open = localStorage.getItem("atlas_man_" + tabKey()) === "1"; } catch {}
  return `<section class="tabhead" style="--c:${T.cor}" aria-label="Sobre esta aba">
    <div class="thcov" aria-hidden="true"><svg viewBox="0 0 600 112" preserveAspectRatio="xMaxYMid slice">${coverScene(T.cena)}</svg></div>
    <div class="thtx"><span class="thk">Missão</span><p>${esc(T.missao)}</p>
      <details class="thman"${open ? " open" : ""} data-man="${tabKey()}"><summary>${ic("book")}Como usar</summary><div class="thmb"><ol>${T.manual.map(x => `<li>${esc(x)}</li>`).join("")}</ol>${T.resolve ? `<p class="muted small"><b>Resolve:</b> ${esc(T.resolve)}${T.entra ? ` · <b>Recebe:</b> ${esc(T.entra)}` : ""}${T.sai ? ` · <b>Alimenta:</b> ${esc(T.sai)}` : ""}</p>` : ""}</div></details></div>
  </section>`;
}
document.addEventListener("toggle", e => { const d = e.target; if (d.matches?.("details.thman")) try { localStorage.setItem("atlas_man_" + d.dataset.man, d.open ? "1" : "0"); } catch {} }, true);

/* ---------------------------------------------------------------- Mapa do Atlas: estrutura, fluxo e lacunas */
const MAPA_GRUPOS = [
  ["O dia", ["hoje", "painel", "rotina", "diario"], "Começar o dia, registrar o que aconteceu, escrever o que importa."],
  ["Vida interior", ["jornada", "mentores"], "Prática, valores e conselho."],
  ["Áreas", ["fin", "saude", "hab", "metas", "pessoas", "cresc", "carreira", "idiomas", "lazer", "casa", "roda"], "Cada área com seus registros, relatório e manual."],
  ["Laboratório", ["cruz", "semana", "radar", "exp", "capitulos", "dupla"], "Entender padrões, fechar ciclos, testar mudanças."],
  ["Sistema", ["dados", "integ", "privacidade", "ajustes"], "Dados, conexões e limites."],
];
const MAPA_FLUXO = [
  ["painel", "saude", "sono, humor, energia, treino"], ["painel", "fin", "gastos"], ["painel", "hab", "hábitos feitos"], ["painel", "jornada", "sessões de prática"], ["painel", "diario", "o texto do dia"], ["rotina", "idiomas", "blocos ocupados saem do tempo de estudo"], ["rotina", "hoje", "a rotina do dia"], ["integ", "rotina", "compromissos do Google Calendar"],
  ["carreira", "fin", "salário → TFR e previdência"], ["carreira", "metas", "objetivos e ações"], ["carreira", "idiomas", "inglês técnico como gap"], ["pessoas", "carreira", "contatos de trabalho → Rede"],
  ["idiomas", "cresc", "horas de estudo"], ["casa", "fin", "conta paga → lançamento"], ["fin", "hoje", "orçamento → ideias que cabem no bolso"], ["lazer", "hoje", "gostos → ideias para sair da rotina"],
  ["saude", "cruz", "séries diárias"], ["cruz", "exp", "hipótese para testar"], ["metas", "hoje", "o que vence"], ["semana", "hoje", "prioridades"],
];
const MAPA_SUGESTOES = [
  ["Saúde preventiva", "Exames, vacinas, consultas e receitas, com o medico di base e o CUP para marcar pelo SSN. Lacuna: a Saúde mede o dia a dia, mas não lembra do check-up anual nem guarda resultados.", "pulse"],
  ["Alimentação & cardápio", "Cardápio da semana que gera a lista de compras da Casa e estima o custo. Lacuna: a lista de compras hoje é manual e não conversa com o que você vai cozinhar.", "leaf"],
  ["Mobilidade", "Carro ou transporte: bollo, revisione, seguro, manutenção e o custo por km; ou o abbonamento GTT. Lacuna: prazos com multa que não aparecem em nenhuma aba.", "arrow"],
  ["Família no Brasil", "Datas, ligações com fuso horário, visitas planejadas e ajuda financeira, ligada a Itália & Brasil e Relações. Lacuna: hoje está espalhado em três abas.", "family"],
];
function pMapa() {
  const nm = k => TAB_INFO[k] && NAV.flatMap(g => g[1]).find(x => x[0] === k);
  return `<div class="mapa">
    ${MAPA_GRUPOS.map(([g, ks, d]) => `<section class="pn"><h2>${esc(g)} <small>${esc(d)}</small></h2><div class="mapag">${ks.filter(nm).map(k => { const T = TAB_INFO[k], n = nm(k); return `<a class="mapai" href="#${k}" style="--c:${T.cor}"><div class="mapcov" aria-hidden="true"><svg viewBox="0 0 600 112" preserveAspectRatio="xMaxYMid slice">${coverScene(T.cena)}</svg></div><b>${ic(n[2])}${esc(n[1])}</b><span>${esc(T.missao)}</span><small><b>Resolve:</b> ${esc(T.resolve)}</small><small class="muted"><b>Capa:</b> ${esc(T.foto)}</small></a>`; }).join("")}</div></section>`).join("")}
    <section class="pn"><h2>${ic("arrow")}Para onde os dados vão <small>cada dado é registrado uma vez e aparece onde é útil</small></h2><div class="hscroll"><table class="dt"><thead><tr><th>De</th><th></th><th>Para</th><th>O quê</th></tr></thead><tbody>${MAPA_FLUXO.map(([a, b, t]) => `<tr><td><a class="lnk" href="#${a}">${esc(pageTitle(a))}</a></td><td>→</td><td><a class="lnk" href="#${b}">${esc(pageTitle(b))}</a></td><td>${esc(t)}</td></tr>`).join("")}</tbody></table></div></section>
    <section class="pn"><h2>${ic("plus")}Abas que ainda faltam <small>em ordem de utilidade para a sua rotina</small></h2><ol class="mapsug">${MAPA_SUGESTOES.map(([t, d, i]) => `<li>${ic(i)}<div><b>${esc(t)}</b><p>${esc(d)}</p></div></li>`).join("")}</ol></section>
  </div>`;
}
